index.bs
index.html

Fix #14
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/15.html" title="Last updated on Apr 24, 2019, 12:26 AM UTC (2f27431)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/15/5766ff9...huningxin:2f27431.html" title="Last updated on Apr 24, 2019, 12:26 AM UTC (2f27431)">Diff</a>

Add Intel WebNN POC API as foundation spec

---

index.bs
index.html

fix #16
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/22.html" title="Last updated on Jul 2, 2019, 8:11 AM UTC (bdc0e8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/22/635339e...huningxin:bdc0e8f.html" title="Last updated on Jul 2, 2019, 8:11 AM UTC (bdc0e8f)">Diff</a>

Simplify the graph building API

---

index.bs
index.html

***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/31.html" title="Last updated on Oct 15, 2019, 9:29 AM UTC (9f9be2e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/31/8968255...9f9be2e.html" title="Last updated on Oct 15, 2019, 9:29 AM UTC (9f9be2e)">Diff</a>

Explainer spec link

---

index.bs
index.html

***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/38.html" title="Last updated on Jan 22, 2020, 10:41 AM UTC (9bd89ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/38/7564bc5...9bd89ed.html" title="Last updated on Jan 22, 2020, 10:41 AM UTC (9bd89ed)">Diff</a>

Add a co-editor

---

op_compatibility/matmul.md

It is based on https://github.com/webmachinelearning/webnn/issues/27#issuecomment-593207390
@anssiko @wchao1115 , please take a look. Thanks!

Add matmul compat table

---

index.bs
index.html

***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/59.html" title="Last updated on May 12, 2020, 11:53 PM UTC (ba8b42d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/59/6d0b502...huningxin:ba8b42d.html" title="Last updated on May 12, 2020, 11:53 PM UTC (ba8b42d)">Diff</a>

Fix a typo

---

index.bs
index.html

This PR is to add concat according to [r01](https://www.w3.org/2020/04/30-webmachinelearning-minutes.html#r01) of WebML CG Teleconference – 30 April 2020.
> RESOLUTION: Add elementwise add, elementwise multiply, concatenation, and reshape ops to the WebNN API
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/55.html" title="Last updated on May 14, 2020, 3:18 PM UTC (7192c61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/55/97be978...huningxin:7192c61.html" title="Last updated on May 14, 2020, 3:18 PM UTC (7192c61)">Diff</a>

Add concat

---

index.bs
index.html

@anssiko Thanks for improving the WebNN Spec, for use cases we may lack of some NLP or RNN use cases, for example the Noise Suppression becomes popular than before. PTAL.
***
<a href="https://pr-preview.s3.amazonaws.com/ibelem/webnn/pull/61.html" title="Last updated on May 29, 2020, 8:26 AM UTC (3a8883d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/61/1bed149...ibelem:3a8883d.html" title="Last updated on May 29, 2020, 8:26 AM UTC (3a8883d)">Diff</a>

[use case] Noise Suppression

---

index.bs
index.html

As @anssiko mentioned in [WebML CG call 11 June](https://www.w3.org/2020/06/11-webmachinelearning-minutes.html#t04), 
> as a related matter, I'd like us to keep https://‌webmachinelearning.github.io/‌webnn/#acknowledgements updated
This PR is adding contributors into the acknowledgements. Please let me know if I missed anyone.
@anssiko @wchao1115 , please help review. Thanks!

Update the acknowledgements

---

index.bs
index.html

Fix #67 
@wchao1115 @RafaelCintron @jbingham @anssiko , please take a look. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/69.html" title="Last updated on Jun 11, 2020, 6:44 AM UTC (088fb01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/69/12d9dfe...huningxin:088fb01.html" title="Last updated on Jun 11, 2020, 6:44 AM UTC (088fb01)">Diff</a>

Set inputs and outputs by string key

---

index.bs
index.html

***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/77.html" title="Last updated on Jun 29, 2020, 9:49 AM UTC (f93d125)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/77/0479212...f93d125.html" title="Last updated on Jun 29, 2020, 9:49 AM UTC (f93d125)">Diff</a>

Link introduction to the explainer

---

index.bs
index.html

Fix https://github.com/webmachinelearning/webnn/pull/109#discussion_r510441256
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/110.html" title="Last updated on Oct 23, 2020, 2:26 AM UTC (403afbc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/110/cdb1695...huningxin:403afbc.html" title="Last updated on Oct 23, 2020, 2:26 AM UTC (403afbc)">Diff</a>

Change minValue and maxValue of clamp to optional

---

explainer.md

Changes include:
1. fixed syntax issues
2. fixed eslint issues
3. added the output values

Fix the basic example in explainer

---

index.bs

- Fixed typos including multilication in ModelBuilder part
***
<a href="https://pr-preview.s3.amazonaws.com/wonsuk73/webnn/pull/118.html" title="Last updated on Nov 2, 2020, 1:25 PM UTC (0e7adfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/118/25088bd...wonsuk73:0e7adfc.html" title="Last updated on Nov 2, 2020, 1:25 PM UTC (0e7adfc)">Diff</a>

Fixed typos in descriptions for ModelBuilder and use cases

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/154.html" title="Last updated on Mar 23, 2021, 12:42 AM UTC (ac3f8a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/154/8a564a1...huningxin:ac3f8a2.html" title="Last updated on Mar 23, 2021, 12:42 AM UTC (ac3f8a2)">Diff</a>

Add the operation level execution use case

---

index.bs

fix #142
@RafaelCintron @cynthia
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/163.html" title="Last updated on Apr 16, 2021, 1:09 AM UTC (ecd9eab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/163/8addd0a...huningxin:ecd9eab.html" title="Last updated on Apr 16, 2021, 1:09 AM UTC (ecd9eab)">Diff</a>

Expose interfaces to DedicatedWorker

---

index.bs

fix #171
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/172.html" title="Last updated on May 24, 2021, 2:14 AM UTC (e307449)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/172/45346b4...huningxin:e307449.html" title="Last updated on May 24, 2021, 2:14 AM UTC (e307449)">Diff</a>

Support broadcasting for gemm

---

CODE_OF_CONDUCT.md
LICENSE.md
index.bs
w3c.json

leaving as draft until the WG confirms its intent to adopt the spec
the index.bs update depends on https://github.com/tabatkins/bikeshed/pull/2075
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/178.html" title="Last updated on Jun 11, 2021, 9:20 AM UTC (2b9e7fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/178/75909b7...2b9e7fb.html" title="Last updated on Jun 11, 2021, 9:20 AM UTC (2b9e7fb)">Diff</a>

Adapt repo & spec for WG adoption

---

Makefile

Reinstate Makefile to help local testing

---

index.bs

Add a short overview subsection to discuss and cover semantic and operational aspects of the API. (This is primarily motivated by the discussion in the issue about introducing terminology, such as views: https://github.com/webmachinelearning/webnn/issues/150 )
***
<a href="https://pr-preview.s3.amazonaws.com/gramalingam/webnn/pull/196.html" title="Last updated on Aug 3, 2021, 6:19 PM UTC (0471426)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/196/31a71f6...gramalingam:0471426.html" title="Last updated on Aug 3, 2021, 6:19 PM UTC (0471426)">Diff</a>

Add overview subsection

---

index.bs

Fix #139
FYI @cynthia @dontcallmedom
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/202.html" title="Last updated on Aug 12, 2021, 8:29 AM UTC (5a554b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/202/dc85541...5a554b6.html" title="Last updated on Aug 12, 2021, 8:29 AM UTC (5a554b6)">Diff</a>

Add introduction, note ML JS frameworks as primary consumers

---

index.bs

Fix #89
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/213.html" title="Last updated on Sep 16, 2021, 3:33 PM UTC (df334b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/213/bd732ee...df334b9.html" title="Last updated on Sep 16, 2021, 3:33 PM UTC (df334b9)">Diff</a>

Add TAG and PING to Acknowledgements

---

index.bs

fix #212
@wchao1115 @pyu10055 @anssiko , PTAL.
cc @Honry
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/214.html" title="Last updated on Oct 25, 2021, 9:14 AM UTC (21a82d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/214/35b4120...huningxin:21a82d8.html" title="Last updated on Oct 25, 2021, 9:14 AM UTC (21a82d8)">Diff</a>

Split transposed convolution to convTranspose2d

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/227.html" title="Last updated on Nov 11, 2021, 2:56 PM UTC (2b16e72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/227/5ddb8ad...2b16e72.html" title="Last updated on Nov 11, 2021, 2:56 PM UTC (2b16e72)">Diff</a>

Add Ethical Considerations

---

index.bs

A minor drive-by typo fix that caught my eye.

Typo fix implemenation -> implementation

---

index.bs

Fix #258
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/260.html" title="Last updated on Mar 22, 2022, 3:18 PM UTC (eb7de71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/260/2ea57d1...eb7de71.html" title="Last updated on Mar 22, 2022, 3:18 PM UTC (eb7de71)">Diff</a>

Replace usage of "responsible document"

---

index.bs

Add Draft Note reference
Following https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2022Jun/0007.html
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/277.html" title="Last updated on Jun 28, 2022, 10:58 AM UTC (fd17613)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/277/026e706...fd17613.html" title="Last updated on Jun 28, 2022, 10:58 AM UTC (fd17613)">Diff</a>

Update Ethical Considerations

---

index.bs

Fix #280
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/286.html" title="Last updated on Sep 1, 2022, 1:00 PM UTC (0740090)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/286/92edaf7...0740090.html" title="Last updated on Sep 1, 2022, 1:00 PM UTC (0740090)">Diff</a>

Address PING review feedback

---

index.bs

- The API is defined using a secure context, there are no description about this
- So it needs to add some descriptions about this in Security Considerations part
***
<a href="https://pr-preview.s3.amazonaws.com/wonsuk73/webnn/pull/297.html" title="Last updated on Oct 13, 2022, 9:17 AM UTC (e3d5ff2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/297/c2b9fc7...wonsuk73:e3d5ff2.html" title="Last updated on Oct 13, 2022, 9:17 AM UTC (e3d5ff2)">Diff</a>

Add secure contexts description to Security Considerations

---

index.bs

fix #289
@wchao1115 @anssiko @wacky6, please take a look, thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/291.html" title="Last updated on Sep 5, 2022, 6:43 AM UTC (80a3917)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/291/39951a0...huningxin:80a3917.html" title="Last updated on Sep 5, 2022, 6:43 AM UTC (80a3917)">Diff</a>

Change newShape of reshape to a sequence of nullable unsigned long

---

index.bs

Fix #327
Note that web specs do not incorporate performance data or numbers, thus I worded this as "can provide a significant performance improvement".
FYI (and thanks!) @wacky6
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/331.html" title="Last updated on Jan 23, 2023, 3:35 PM UTC (bb79832)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/331/d82ee20...bb79832.html" title="Last updated on Jan 23, 2023, 3:35 PM UTC (bb79832)">Diff</a>

Note fused activations can improve performance

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/Honry/webnn/pull/349.html" title="Last updated on Feb 16, 2023, 8:45 AM UTC (c90bcb3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/349/817c5a5...Honry:c90bcb3.html" title="Last updated on Feb 16, 2023, 8:45 AM UTC (c90bcb3)">Diff</a>

Fix a minor error in Example 7

---

index.bs

fix #356
@wchao1115 @pyu10055 @anssiko @wacky6 @RafaelCintron , PTAL. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/357.html" title="Last updated on Feb 28, 2023, 6:09 AM UTC (d0686bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/357/14c6670...huningxin:d0686bc.html" title="Last updated on Feb 28, 2023, 6:09 AM UTC (d0686bc)">Diff</a>

Add prelu (Parametric ReLU) into the operation list

---

index.bs

@anssiko @wchao1115 , PTAL.
/cc @fdwr

Fix a typo of elu sample code

---

index.bs

@anssiko @wchao1115 , PTAL.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/389.html" title="Last updated on May 15, 2023, 4:11 AM UTC (b94adf7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/389/a115073...huningxin:b94adf7.html" title="Last updated on May 15, 2023, 4:11 AM UTC (b94adf7)">Diff</a>

Acknowledge Jiewei Qian for Chromium implementation review and feedback

---

index.bs

Add element-wise binary operation algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/408.html" title="Last updated on Jun 21, 2023, 7:59 PM UTC (5f7a507)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/408/c54d842...zolkis:5f7a507.html" title="Last updated on Jun 21, 2023, 7:59 PM UTC (5f7a507)">Diff</a>

Add element-wise binary operation algorithms

---

index.bs

Add the elu() algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/410.html" title="Last updated on Jun 21, 2023, 8:59 PM UTC (5c9190b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/410/c54d842...zolkis:5c9190b.html" title="Last updated on Jun 21, 2023, 8:59 PM UTC (5c9190b)">Diff</a>

Add the elu() algorithm

---

index.bs

Add the gemm() algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/411.html" title="Last updated on Jun 21, 2023, 9:27 PM UTC (eda2dba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/411/c54d842...zolkis:eda2dba.html" title="Last updated on Jun 21, 2023, 9:27 PM UTC (eda2dba)">Diff</a>

Add the gemm() algorithm

---

index.bs

Add the hard-swish algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/414.html" title="Last updated on Jun 22, 2023, 9:20 AM UTC (bc70a12)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/414/c54d842...zolkis:bc70a12.html" title="Last updated on Jun 22, 2023, 9:20 AM UTC (bc70a12)">Diff</a>

Add the hard-swish algorithm

---

index.bs

Add the instance normalization algorithm.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 26, 2023, 12:22 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fzolkis%2Fwebnn%2F7b9fdaf3be6201a6b4ee8a29def8a4ff882efab2%2Findex.bs&force=1&md-warning=not%20ready)
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if …

Add the instance normalization algorithm

---

index.bs

Add the Leaky RELU algorithm
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/416.html" title="Last updated on Jun 26, 2023, 12:40 PM UTC (a6ef2f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/416/c54d842...zolkis:a6ef2f0.html" title="Last updated on Jun 26, 2023, 12:40 PM UTC (a6ef2f0)">Diff</a>

Add the Leaky RELU algorithm

---

index.bs

Add the LSTM and LSTM Cell algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/418.html" title="Last updated on Jun 26, 2023, 1:51 PM UTC (d035242)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/418/c54d842...zolkis:d035242.html" title="Last updated on Jun 26, 2023, 1:51 PM UTC (d035242)">Diff</a>

Add the LSTM and LSTM Cell algorithms

---

index.bs

Add the matmul() algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/419.html" title="Last updated on Jun 26, 2023, 2:13 PM UTC (35a8de7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/419/c54d842...zolkis:35a8de7.html" title="Last updated on Jun 26, 2023, 2:13 PM UTC (35a8de7)">Diff</a>

Add the matmul() algorithm

---

index.bs

Add the pad() algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/420.html" title="Last updated on Jun 26, 2023, 2:21 PM UTC (1b0e8f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/420/c54d842...zolkis:1b0e8f4.html" title="Last updated on Jun 26, 2023, 2:21 PM UTC (1b0e8f4)">Diff</a>

Add the pad() algorithm

---

index.bs

Add the pooling algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/421.html" title="Last updated on Jun 26, 2023, 7:52 PM UTC (3657d7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/421/c54d842...zolkis:3657d7f.html" title="Last updated on Jun 26, 2023, 7:52 PM UTC (3657d7f)">Diff</a>

Add the pooling algorithms

---

index.bs

Add the relu() algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/424.html" title="Last updated on Jun 26, 2023, 7:34 PM UTC (8f39ef2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/424/c54d842...zolkis:8f39ef2.html" title="Last updated on Jun 26, 2023, 7:34 PM UTC (8f39ef2)">Diff</a>

Add the relu() algorithm

---

index.bs

Add the reshape algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/426.html" title="Last updated on Jun 27, 2023, 8:39 AM UTC (869fa53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/426/c54d842...zolkis:869fa53.html" title="Last updated on Jun 27, 2023, 8:39 AM UTC (869fa53)">Diff</a>

Add the reshape algorithm

---

index.bs

Add the slice algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/428.html" title="Last updated on Jun 27, 2023, 3:50 PM UTC (18528db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/428/c54d842...zolkis:18528db.html" title="Last updated on Jun 27, 2023, 3:50 PM UTC (18528db)">Diff</a>

Add the slice algorithm

---

index.bs

Add the softplus algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/430.html" title="Last updated on Jun 27, 2023, 4:10 PM UTC (bfc124b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/430/c54d842...zolkis:bfc124b.html" title="Last updated on Jun 27, 2023, 4:10 PM UTC (bfc124b)">Diff</a>

Add the softplus algorithm

---

index.bs

Add the sigmoid algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/427.html" title="Last updated on Jun 29, 2023, 9:04 AM UTC (ef17659)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/427/542c7e0...zolkis:ef17659.html" title="Last updated on Jun 29, 2023, 9:04 AM UTC (ef17659)">Diff</a>

Add the sigmoid algorithm

---

index.bs

Add the split algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/432.html" title="Last updated on Jun 27, 2023, 4:24 PM UTC (cdc2cc7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/432/c54d842...zolkis:cdc2cc7.html" title="Last updated on Jun 27, 2023, 4:24 PM UTC (cdc2cc7)">Diff</a>

Add the split algorithm

---

index.bs

Add the squeeze() algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/433.html" title="Last updated on Jun 27, 2023, 4:38 PM UTC (a4f36da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/433/c54d842...zolkis:a4f36da.html" title="Last updated on Jun 27, 2023, 4:38 PM UTC (a4f36da)">Diff</a>

Add the squeeze() algorithm

---

index.bs

Add the softsign method.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/431.html" title="Last updated on Jun 29, 2023, 9:23 AM UTC (f33242e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/431/c6711c3...zolkis:f33242e.html" title="Last updated on Jun 29, 2023, 9:23 AM UTC (f33242e)">Diff</a>

Add the softsign method

---

index.bs

Add the tanh algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/434.html" title="Last updated on Jun 29, 2023, 9:24 AM UTC (0f8a85b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/434/c6711c3...zolkis:0f8a85b.html" title="Last updated on Jun 29, 2023, 9:24 AM UTC (0f8a85b)">Diff</a>

Add the tanh algorithm

---

index.bs

A few merge errors accumulated, fixed here.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/437.html" title="Last updated on Jun 29, 2023, 10:30 AM UTC (dbff6e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/437/9ddd4b9...zolkis:dbff6e2.html" title="Last updated on Jun 29, 2023, 10:30 AM UTC (dbff6e2)">Diff</a>

Fix merge errors

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/440.html" title="Last updated on Jul 12, 2023, 4:19 PM UTC (bb94f01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/440/dbff6e2...zolkis:bb94f01.html" title="Last updated on Jul 12, 2023, 4:19 PM UTC (bb94f01)">Diff</a>

Add the command finish steps

---

index.bs

I wanted to acknowledge @xenova @BruceDai @Honry for their contributions, including contributions via the web-platform-tests project.
Please let us know if we're missing some folks and feel free to propose updates to this section when you see great work around you. Thanks for your contributions!
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/554.html" title="Last updated on Feb 5, 2024, 1:32 PM UTC (4f62535)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/554/7ec2e18...4f62535.html" title="Last updated on Feb 5, 2024, 1:32 PM UTC (4f62535)">Diff</a>

Acknowledge more people

---

index.bs

The WG thanks Chai for his major contributions as a co-editor and welcomes Dwayne into his new role.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/561.html" title="Last updated on Feb 8, 2024, 3:10 PM UTC (fc0390d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/561/d1a02f2...fc0390d.html" title="Last updated on Feb 8, 2024, 3:10 PM UTC (fc0390d)">Diff</a>

Editor change

---

index.bs

This matches the Chromium prototype implementation.
Fixes #341
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/584.html" title="Last updated on Feb 26, 2024, 4:44 PM UTC (55ebb8a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/584/abd434d...inexorabletash:55ebb8a.html" title="Last updated on Feb 26, 2024, 4:44 PM UTC (55ebb8a)">Diff</a>

Bug fix: Validate MLGraph's context in MLContext's compute()

---

index.bs

Fix #326
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/587.html" title="Last updated on Feb 27, 2024, 1:22 PM UTC (cb26ac4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/587/a904425...huningxin:cb26ac4.html" title="Last updated on Feb 27, 2024, 1:22 PM UTC (cb26ac4)">Diff</a>

Remove MLAutoPad

---

index.bs

Fixes #562
See the linked issue for details
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/592.html" title="Last updated on Feb 28, 2024, 10:32 PM UTC (6023741)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/592/0de084d...a-sully:6023741.html" title="Last updated on Feb 28, 2024, 10:32 PM UTC (6023741)">Diff</a>

Apply [EnforceRange] to all integer types

---

index.bs

Introduced by me in 1d1b531a c761733a. Oops.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/616.html" title="Last updated on Mar 21, 2024, 8:52 PM UTC (1ed5e99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/616/77696f7...inexorabletash:1ed5e99.html" title="Last updated on Mar 21, 2024, 8:52 PM UTC (1ed5e99)">Diff</a>

Bugfix: Unbalanced autolink brackets

---

explainer.md

Update NSNet2 reference

---

index.bs

per discussion in  #615 , describe that WebNN allows graph without inputs, and suggest implementations how to support that.
fix #615
***
<a href="https://pr-preview.s3.amazonaws.com/philloooo/webnn/pull/632.html" title="Last updated on Apr 2, 2024, 7:34 PM UTC (3630cae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/632/60b8e0a...philloooo:3630cae.html" title="Last updated on Apr 2, 2024, 7:34 PM UTC (3630cae)">Diff</a>

add a note for empty input

---

index.bs

To fix #626 
PTAL, thanks! @huningxin
***
<a href="https://pr-preview.s3.amazonaws.com/mingmingtasd/webnn/pull/628.html" title="Last updated on Apr 4, 2024, 1:13 AM UTC (58d76da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/628/60b8e0a...mingmingtasd:58d76da.html" title="Last updated on Apr 4, 2024, 1:13 AM UTC (58d76da)">Diff</a>

Define Gelu operation

---

README.md

Updated per https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

README: Fix badge image URL

---

index.bs

Resolves #614
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/665.html" title="Last updated on Apr 29, 2024, 9:44 PM UTC (e2abe1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/665/9f0f45a...inexorabletash:e2abe1c.html" title="Last updated on Apr 29, 2024, 9:44 PM UTC (e2abe1c)">Diff</a>

Add note about no-op graphs

---

index.bs

Fixes #686
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/687.html" title="Last updated on May 14, 2024, 6:31 PM UTC (3008287)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/687/5d94426...inexorabletash:3008287.html" title="Last updated on May 14, 2024, 6:31 PM UTC (3008287)">Diff</a>

Validate layerNormalization options.axes

---

index.bs

Fixes #693
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/698.html" title="Last updated on May 30, 2024, 9:11 PM UTC (e77cf72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/698/0f7911d...inexorabletash:e77cf72.html" title="Last updated on May 30, 2024, 9:11 PM UTC (e77cf72)">Diff</a>

Add int64/uint64 to ArrayBufferView compatibility table

---

.github/workflows/auto-publish.yml

Context:
https://github.com/speced/bikeshed/issues/2861#issuecomment-2131233140

Workflows: use ubuntu-latest to get up-to-date python/Bikeshed

---

index.bs
tools/lint.mjs

Add lint rule, fix a handful of exceptions.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/707.html" title="Last updated on Jun 12, 2024, 11:31 PM UTC (c337d90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/707/74b9831...inexorabletash:c337d90.html" title="Last updated on Jun 12, 2024, 11:31 PM UTC (c337d90)">Diff</a>

Style: Ensure algorithm steps end in '.' or ':'

---

docs/IssueTriage.md

For discussions about device selection mechanisms.

Process: Add "device selection" label

---

tools/lint.mjs

As suggested by @inexorabletash in https://github.com/webmachinelearning/webnn/pull/717/files/9c9bfa2a5c20f711aad516192088fc6d7b97fb36#r1672817903

Ensure every method dfn is correctly associated with an interface

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/733.html" title="Last updated on Jul 22, 2024, 11:53 PM UTC (0a5839d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/733/487a992...inexorabletash:0a5839d.html" title="Last updated on Jul 22, 2024, 11:53 PM UTC (0a5839d)">Diff</a>

Editorial: Fix an instance of "nchw" enum member styling/linking

---

index.bs

Update NumPy URLs, too.
Resolves #378
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/745.html" title="Last updated on Jul 30, 2024, 5:54 PM UTC (fd5e2fe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/745/8734bea...inexorabletash:fd5e2fe.html" title="Last updated on Jul 30, 2024, 5:54 PM UTC (fd5e2fe)">Diff</a>

Add blurb explaining broadcasting in more detail

---

index.bs

Fixes #758
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/764.html" title="Last updated on Sep 24, 2024, 4:43 PM UTC (e2ad28b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/764/53a24db...a-sully:e2ad28b.html" title="Last updated on Sep 24, 2024, 4:43 PM UTC (e2ad28b)">Diff</a>

Make MLOperandDescriptor.shape required

---

index.bs

Consolidate resources and projects supporting the specification under the custom "Other" header.
This PR will help address TAG feedback on multi-implementer support https://github.com/w3ctag/design-reviews/issues/933#issuecomment-2192643962 by making the implementation status tracker visible in the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/769.html" title="Last updated on Oct 22, 2024, 3:03 PM UTC (36fed2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/769/81a355a...36fed2f.html" title="Last updated on Oct 22, 2024, 3:03 PM UTC (36fed2f)">Diff</a>

Add Implementation Status to metadata

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/782.html" title="Last updated on Nov 9, 2024, 12:59 AM UTC (e536886)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/782/11f85ff...inexorabletash:e536886.html" title="Last updated on Nov 9, 2024, 12:59 AM UTC (e536886)">Diff</a>

Wording: Fix some minor typos and grammar glitches

---

index.bs

This PR is to fix **gru** emulation error of #801.
@fdwr @huningxin PTAL, thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/BruceDai/webnn/pull/803.html" title="Last updated on Jan 16, 2025, 2:50 AM UTC (99d97ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/803/df555e1...BruceDai:99d97ee.html" title="Last updated on Jan 16, 2025, 2:50 AM UTC (99d97ee)">Diff</a>

Bugfix: Fix emulation error of gru by 'backward' and 'both' direction options

---

index.bs

As discussed at https://www.w3.org/2025/01/30-webmachinelearning-minutes.html#01a1
Resolves #804
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/823.html" title="Last updated on Feb 24, 2025, 10:41 PM UTC (b76d7aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/823/9f58451...inexorabletash:b76d7aa.html" title="Last updated on Feb 24, 2025, 10:41 PM UTC (b76d7aa)">Diff</a>

Expose WebNN API to shared workers and service workers

---

tools/lint.mjs

Explicit comments and some refactoring to make the code somewhat more self-documenting, to support future maintenance efforts.

Tooling: Better documentation for how linting works

---

cache-explainer.md
index.bs

This synthesis is based on WG discussion in #807, Chromium Design Doc and prototype implementation findings.
With credits to @reillyeon for the API proposal, @shiyi9801 for the prototype implementation, @huningxin for the Chromium Design Doc, and to the entire WG for active issue discussion.
The aim was to try keep this as a ~1-pager, so we can iterate on this more easily.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/862.html" title="Last updated on Jun 17, 2025, 9:43 AM UTC (1e1bc1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/862/61d4d5a...1e1bc1c.html" title="Last updated on Jun 17, 2025, 9:43 AM UTC (1e1bc1c)">Diff</a>

Add WebNN MLGraph Cache Explainer
