webmachinelearning/webnn

index.bs
index.html

Acknowledge participants who contributed to the use case definition in #2.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/4.html" title="Last updated on Dec 21, 2018, 11:35 AM UTC (d110da2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/4/d4ba82b...d110da2.html" title="Last updated on Dec 21, 2018, 11:35 AM UTC (d110da2)">Diff</a>

Add acknowledgements

---

index.bs
index.html

'Low-level' and 'high-level' are ambiguous in this context.
Partial fix to #8.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/10.html" title="Last updated on Feb 18, 2019, 10:42 AM UTC (e48c3ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/10/94c6171...e48c3ce.html" title="Last updated on Feb 18, 2019, 10:42 AM UTC (e48c3ce)">Diff</a>

Rename use case subsections

---

explainer.md

At [F2F](https://www.w3.org/2019/09/20-webmachinelearning-minutes.html#x02) we agreed it'd be good to start evolve the [explainer](https://github.com/webmachinelearning/webnn/blob/master/explainer.md) document in parallel with the [formal spec](https://webmachinelearning.github.io/webnn/).
Here's my first stab at the hardware support section of that document, PTAL @huningxin @nsthorat and others.
We should consider the explainer document a place where we write down our collective thoughts without needing to worry too much if those will change. By this definition, the explainer is expected evolve and change significantly and everyone is encouraged to contribute. It is a markdown file, so low barrier to entry :-)
To contract with the spec, I'd propose we put things in the formal spec that …

Add target hardware section to explainer

---

index.bs
index.html

fix #39
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/46.html" title="Last updated on Feb 26, 2020, 6:32 AM UTC (3263911)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/46/c8fdf66...huningxin:3263911.html" title="Last updated on Feb 26, 2020, 6:32 AM UTC (3263911)">Diff</a>

Remove Compilation.finish and setPreference

---

index.bs
index.html

According to [the resolution of 6 Feb CG meeting](https://www.w3.org/2020/02/06-webmachinelearning-minutes.html#x02), 
> RESOLUTION: Add conv2d and matMul op definitions to WebNN API
creating this PR.
This PR is based on conv2d signature proposed by @nsthorat in #28. Regarding to the [conv2d compatibility table](https://github.com/webmachinelearning/webnn/blob/master/op_compatibility/conv2d.md), *strides* for N and C dimension are not supported by all investigated APIs, so keep *strides* just for spatial dimensions.
@nsthorat @wchao1115 @anssiko , please take a look. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/43.html" title="Last updated on Feb 27, 2020, 1:50 AM UTC (7cf9f18)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/w …

Add conv2d

---

index.bs
index.html

This PR is based on matmul [signature proposal](https://github.com/webmachinelearning/webnn/issues/27#issue-494290232) and [compatibility table](https://github.com/webmachinelearning/webnn/blob/master/op_compatibility/matmul.md).
@wchao1115 @nsthorat @BenjaminPoulain and @anssiko, please take a look. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/49.html" title="Last updated on Mar 25, 2020, 2:25 AM UTC (2fd2baf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/49/30d4117...huningxin:2fd2baf.html" title="Last updated on Mar 25, 2020, 2:25 AM UTC (2fd2baf)">Diff</a>

Add matmul

---

index.bs
index.html

Update CompilationPreference to follow WebGL convention for context creation. Update the code sample to show how a certain compilation could fail such as when the model uses data type not supported by the hardware, and how to recover from the failure. #36
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/50.html" title="Last updated on Apr 4, 2020, 7:33 AM UTC (af16a69)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/50/b341ec2...af16a69.html" title="Last updated on Apr 4, 2020, 7:33 AM UTC (af16a69)">Diff</a>

How to handle a failing compilation

---

index.bs
index.html

This PR is to add spec texts of element-wise add and multiply according to [r01](https://www.w3.org/2020/04/30-webmachinelearning-minutes.html#r01) of WebML CG Teleconference – 30 April 2020.
> RESOLUTION: Add elementwise add, elementwise multiply, concatenation, and reshape ops to the WebNN API
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/54.html" title="Last updated on May 14, 2020, 2:03 AM UTC (7f8b1b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/54/928572e...huningxin:7f8b1b5.html" title="Last updated on May 14, 2020, 2:03 AM UTC (7f8b1b5)">Diff</a>

Add spec text of add and mul

---

index.bs
index.html

This PR is to add reshape according to [r01](https://www.w3.org/2020/04/30-webmachinelearning-minutes.html#r01) of WebML CG Teleconference – 30 April 2020.
> RESOLUTION: Add elementwise add, elementwise multiply, concatenation, and reshape ops to the WebNN API
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/57.html" title="Last updated on May 14, 2020, 3:24 PM UTC (f73fd68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/57/ad86cb4...huningxin:f73fd68.html" title="Last updated on May 14, 2020, 3:24 PM UTC (f73fd68)">Diff</a>

Add reshape

---

index.bs
index.html

Per the [first wave models](https://github.com/webmachinelearning/webnn/blob/master/op_compatibility/first_wave_models.md), `relu` is required by SqueezeNet, MobileNet and ResNet. `relu` can be implemented by element-wise `max`.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/62.html" title="Last updated on May 25, 2020, 3:09 AM UTC (f75101e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/62/c14010b...huningxin:f75101e.html" title="Last updated on May 25, 2020, 3:09 AM UTC (f75101e)">Diff</a>

Add relu and max

---

index.bs
index.html

Per the [first wave models](https://github.com/webmachinelearning/webnn/blob/master/op_compatibility/first_wave_models.md), `leakyRelu` is required by TinyYOLOV2 model. `leakyRelu` can be implemented by element-wise `add`, `mul`, `max` and `min` where `min` is being added in this PR.
@wchao1115 @gramalingam, please take a look. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/63.html" title="Last updated on Jun 5, 2020, 7:22 AM UTC (95866d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/63/d7b8e8d...huningxin:95866d2.html" title="Last updated on Jun 5, 2020, 7:22 AM UTC (95866d2)">Diff</a>

Add leakyRelu and min

---

index.bs
index.html

This PR is a follow-up to @pyu10055 's suggestion in [WebML CG June 25 meeting](https://www.w3.org/2020/06/25-webmachinelearning-minutes.html#t04)
> Ping: having the weights directly in the code would make for a clearer example
This PR changes to set the concrete values for constant and input tensors.
There is a [running version](https://jsfiddle.net/ningxinhu/kd1wvjop/) by using an API polyfill based on TF.js. I suppose it would be help for code review.
@pyu10055, @wchao1115 and @anssiko , please take a look. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/80.html" title="Last updated on Jul 2, 2020, 4:13 AM UTC (a568ca5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/80/68af5cd...huningxin:a568ca5.html" title="Last …

Simplify the examples

---

index.bs
index.html

It is appropriate to note the polyfill and samples in the spec header to raise awareness of these closely related projects.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/91.html" title="Last updated on Sep 21, 2020, 2:00 PM UTC (decfa58)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/91/059dff1...decfa58.html" title="Last updated on Sep 21, 2020, 2:00 PM UTC (decfa58)">Diff</a>

Add polyfill and samples to spec header

---

.github/workflows/ci.yaml
README.md

Add the bikeshield build as the initial CI (continuous integration). It would help us to detect the spec issue such as https://github.com/webmachinelearning/webnn/pull/100 and https://github.com/webmachinelearning/webnn/pull/101#discussion_r502984105 as early as possible. For example, it could report spec error as https://github.com/huningxin/webnn/runs/1239704785?check_suite_focus=true.
@anssiko @wchao1115 @pyu10055 @wonsuk73 , PTAL. Thanks!

Add the initial CI

---

index.bs

- Web NN API is to access the hardware acceleration for machine learning. So it is only need to be exposed in secure contexts. It means that this API is only available over HTTPS.
- removed "Models" from biblio because it isn't unused any more
***
<a href="https://pr-preview.s3.amazonaws.com/wonsuk73/webnn/pull/115.html" title="Last updated on Oct 30, 2020, 5:32 AM UTC (25088bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/115/058a81a...wonsuk73:25088bd.html" title="Last updated on Oct 30, 2020, 5:32 AM UTC (25088bd)">Diff</a>

Added extended attributes to Web IDL definition

---

index.bs

There are syntax error and lint errors of the example. This PR fixes them. 
The idea is to keep aligned with the webnn example update as https://github.com/webmachinelearning/webnn-samples/pull/19. Here is a preview version: https://huningxin.github.io/webnn-samples/code/?example=simple_graph.js
@anssiko @wchao1115 @pyu10055 , please take a look. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/104.html" title="Last updated on Oct 28, 2020, 2:48 PM UTC (c94c0a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/104/058a81a...huningxin:c94c0a4.html" title="Last updated on Oct 28, 2020, 2:48 PM UTC (c94c0a4)">Diff</a>

Fix example

---

index.bs

It should reshape the 2-D output of gruCell to 3-D tensor.
The fix is verified by the webnn-polyfill gru implementation: https://github.com/huningxin/webnn-polyfill/blob/gru/src/nn/ops/gru.ts#L113
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/117.html" title="Last updated on Oct 31, 2020, 5:11 AM UTC (bcdb16b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/117/3dd5bbf...huningxin:bcdb16b.html" title="Last updated on Oct 31, 2020, 5:11 AM UTC (bcdb16b)">Diff</a>

Fix the gru pseudo sample code

---

explainer.md

Correct mismatched references between the original version of NSNet and the link to the revisioned NSNet2 in the scenario section. Adjust some wordings in the alternatives section.

Correct mismatched references in NSNet baseline sample

---

index.bs

#108 
- Extend the `conv2d` operation to support transposed convolution, an essential upsample tool for encoder-decoder models.
- Add `instanceNormalization` in addition to batch-normalization. Instance-normalization is a fused operation for a normalization subgraph that computes the mean and variance values per-feature instance on the fly.
- Replace the `sqrt` unary operation with a more generic `pow` binary operation used by the normalization process.
- Add `pad` operation that supports all 4 padding modes found in various frameworks.
- Add `resample` operation to support both upsampling and downsampling of feature instances. This operation is used in the ONNX version of the style-transfer models.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/123.html" …

Support style-transfer models with changes/additions to the following operations

---

index.bs

#125 
Two additions to the current [conv2d](https://webmachinelearning.github.io/webnn/#api-modelbuilder-conv2d) operator. 
- TensorFlow, TensorFlow-Lite, and NNAPI support different set of filter layouts separately from the input tensor layout formats. 
- ONNX and PyTorch support an additional 1-D bias tensor.
@gramalingam
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/130.html" title="Last updated on Jan 26, 2021, 4:19 AM UTC (aec6d4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/130/aaa03be...aec6d4e.html" title="Last updated on Jan 26, 2021, 4:19 AM UTC (aec6d4e)">Diff</a>

Support a separate filter layout formats and the optional bias tensor.

---

explainer.md

Update the NSNet2 example code base on https://webmachinelearning.github.io/webnn-samples/nsnet2/ and add the link into the explainer.
@wchao1115 @anssiko , please take a look. Thanks!

Update the NSNet2 example and add its link

---

security-privacy.md

Add responses to the Self-Review Questionnaire: Security and Privacy

---

index.bs

- #133 Move Relu into the unary operator section.
- #134 Clarify in the descriptions of BatchNormalization and InstanceNormalization
- #137 Clarify in the descriptions of Reshape and Squeeze about the content-neutral nature of the operations.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/144.html" title="Last updated on Feb 20, 2021, 4:53 AM UTC (44870de)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/144/356de2d...44870de.html" title="Last updated on Feb 20, 2021, 4:53 AM UTC (44870de)">Diff</a>

Addressing TAG review issue#133, 134, and 137

---

explainer.md
index.bs

- Create context from external sources e.g. WebGLRenderingContext and WebGPU device (#135)
- Make power preference part of context creation options.
- Constant operands can be created from either WebGL or WebGPU buffers
- Model inputs and outputs can be bound with WebGL or WebGPU textures
- Prefix all types with "ML". Simplify "NeuralNetworkContext" to just "MLContext" (#141)
- Switch to use constructor for MLModelBuilder instead of factory method (#136)
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/149.html" title="Last updated on Mar 15, 2021, 6:06 AM UTC (c43ed52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/149/4db4c69...c43ed52.html" title="Last updated on Mar 15, 2021, 6:06 AM UTC (c43ed52)">Diff</a>

WebGL and WebGPU interops

---

.github/dependabot.yml
.github/workflows/build.yaml
.github/workflows/deploy.yaml

Verified with my forked repo: https://github.com/huningxin/webnn/actions/runs/656212010
@wchao1115 @anssiko , please take a look. Hope it fixes the the gh-pages deployment issue.

Fix build and deploy github actions

---

index.bs

The WebGPU API spec is not in the bibliography databases yet,
so it must be manually added to make it appear in the Normative
References section.
https://tabatkins.github.io/bikeshed/#biblio
https://tabatkins.github.io/bikeshed/#biblio-manual
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/155.html" title="Last updated on Mar 22, 2021, 7:31 AM UTC (c430fb3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/155/8a564a1...c430fb3.html" title="Last updated on Mar 22, 2021, 7:31 AM UTC (c430fb3)">Diff</a>

Add [WEBGPU] custom bibliography entry

---

index.bs

@wchao1115 @pyu10055 @anssiko , PTAL.
Hopefully, it would fix #140 @cynthia, please also take a look.
Another note is, for the spec of ML device interactions, I found the [timelines](https://gpuweb.github.io/gpuweb/#programming-model-timelines) of WebGPU spec is quite useful. So I adapted and included it in this PR.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/147.html" title="Last updated on Apr 1, 2021, 3:13 PM UTC (380379c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/147/880cd8a...huningxin:380379c.html" title="Last updated on Apr 1, 2021, 3:13 PM UTC (380379c)">Diff</a>

Add the spec text and examples for MLGraph.compute

---

index.bs

fix #160
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/161.html" title="Last updated on Apr 10, 2021, 12:25 AM UTC (4acef27)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/161/0f913d6...huningxin:4acef27.html" title="Last updated on Apr 10, 2021, 12:25 AM UTC (4acef27)">Diff</a>

Support ihwo filter layout of conv2d

---

index.bs

Fix #145
In addition to Permissions Policy Integration (per [integration best practices](https://github.com/w3c/webappsec-permissions-policy/blob/main/integration.md)), this also adds initial steps for `createContext()` to allow integration of the "allowed to use" check.
@wchao1115 you wanted to clarify the context creation prose so if this looks good to you you can base your further work on top of this and augment the steps with more context creation details.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/159.html" title="Last updated on Apr 7, 2021, 3:22 PM UTC (ce01a73)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/159/0f913d6...ce01a73.html" title="Last updated on Apr 7, 2021, 3:22 PM UTC (ce01a73)">Diff</a>

Add Permissions Policy Integration and initial createContext() hooks

---

index.bs

First version based on initial PING review in #119
Fix #122
PTAL @sandandsnow for PING review. We expect to evolve this initial version based on additional feedback.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/170.html" title="Last updated on May 19, 2021, 9:25 AM UTC (1055355)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/170/45346b4...1055355.html" title="Last updated on May 19, 2021, 9:25 AM UTC (1055355)">Diff</a>

Add initial Security and Privacy Considerations sections

---

explainer.md
index.bs

This PR follows the discussion in PR #166 and fixes use case #156. The changes include
1. Change `MLGraphBuilder.build` and `MLGraph.compute` to sync API. 
a. Sync API is easy to use and required by sync wasm lib implementation. 
b. The caller can call the sync API within a webworker to achieve asynchronous https://github.com/webmachinelearning/webnn/issues/156#issuecomment-849665061 @pyu10055 
2. Change `MLGraph.compute` to require pre-allocated output buffers. 
a. For wasm lib, the output buffers are pre-allcoated in wasm memory. 
b. For GPU, it is prohibitively expensive to create GPU resources on the fly as a function call's return value https://github.com/webmachinelearning/webnn/pull/166#discussion_r637575735 @wchao1115 
3. Simplify the the input / output resources binding by …

Support sync API and require pre-allocated output buffers

---

.github/workflows/auto-publish.yml
index.bs

Per https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2021Jun/0011.html
Following FPWD published at https://www.w3.org/TR/2021/WD-webnn-20210622/
(we should probably wait until June 23rd to merge this, to make sure the FPWD isn't overridden by a simple WD)
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/183.html" title="Last updated on Jun 22, 2021, 7:09 AM UTC (19cbf8e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/183/7dd419e...19cbf8e.html" title="Last updated on Jun 22, 2021, 7:09 AM UTC (19cbf8e)">Diff</a>

Set up for automatic publication using Echidna

---

index.bs

The yellow left border otherwise appears also on the top metadata of the spec, making it at odds with the regular look of W3C specs
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/186.html" title="Last updated on Jun 24, 2021, 11:14 AM UTC (35ed6be)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/186/a913875...35ed6be.html" title="Last updated on Jun 24, 2021, 11:14 AM UTC (35ed6be)">Diff</a>

Scope dl highlight to body of spec

---

index.bs

As part of this change, I generalize a way to allow an operator to be created before it is connected to the graph. This makes it possible for fused operators, particularly the various activation functions to be expressed by a generic operator type instead of through an ever-expanding list of enum values, which addresses both #185 and #138. 
Mechanically, a notion of `MLOperator` is defined. This is a definition of a type of operation and not the operation itself, as no input operands are needed in the creation of an operator and no operand is expected from it. The operator will then connect with the rest of the graph via the graph builder once the input operands are ready.  The best example of this mechanic is demonstrated in the note section of the `batchNormalization` opeation where an …

Add activation functions as fused operators to BatchNorm and Conv2d

---

Makefile
index.bs

fix #181 , 
This PR also fixes
- some typo raised by #194
- change the local Makefile to die on error that aligns to the [auto-publish.yml](https://github.com/webmachinelearning/webnn/blob/main/.github/workflows/auto-publish.yml).
@wchao1115  @pyu10055 PTAL. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/195.html" title="Last updated on Jul 21, 2021, 2:25 AM UTC (721ed65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/195/31a71f6...huningxin:721ed65.html" title="Last updated on Jul 21, 2021, 2:25 AM UTC (721ed65)">Diff</a>

Support hard-swish operation

---

index.bs

fix #203
@wchao1115 @pyu10055 @anssiko , PTAL. Thanks!
cc @mingmingtasd
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/206.html" title="Last updated on Aug 30, 2021, 5:40 AM UTC (61d78f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/206/dc85541...huningxin:61d78f1.html" title="Last updated on Aug 30, 2021, 5:40 AM UTC (61d78f1)">Diff</a>

Change min and max values of clamp to float

---

index.bs

fix #192 
@wchao1115 @pyu10055 @anssiko , PTAL. Thanks.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/204.html" title="Last updated on Aug 29, 2021, 12:54 AM UTC (006f05f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/204/dc85541...huningxin:006f05f.html" title="Last updated on Aug 29, 2021, 12:54 AM UTC (006f05f)">Diff</a>

Add default values of scales into resample op

---

index.bs

fix #198 
@wchao1115 @pyu10055 @anssiko , PTAL.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/208.html" title="Last updated on Sep 22, 2021, 6:29 AM UTC (17d1fc5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/208/35b4120...huningxin:17d1fc5.html" title="Last updated on Sep 22, 2021, 6:29 AM UTC (17d1fc5)">Diff</a>

Support rounding type of pool2d operations

---

index.bs

fix #200 
This change supports resample2d:
* resize the spatial dimensions
* specify the input layout
@wchao1115 @pyu10055 @anssiko , please take a look.
cc @fujunwei.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/205.html" title="Last updated on Sep 26, 2021, 2:56 AM UTC (cf99237)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/205/4fc42a4...huningxin:cf99237.html" title="Last updated on Sep 26, 2021, 2:56 AM UTC (cf99237)">Diff</a>

Change resample to resample2d

---

LICENSE.md

This uses the WG license template https://github.com/w3c/licenses/blob/main/WG-LICENSE.md but updates the license from W3C Document License to W3C Software and Document license per https://www.w3.org/2021/04/web-machine-learning-charter.html#licensing

Update LICENSE.md to match WG Charter Licensing section

---

index.bs

Now that we have `webnn` in the wpt tree it is appropriate to link to it from the spec so folks who want to contribute will find the right place. The expectation is the linked test suite at this point of development is WIP.
FYI @brucedai
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/238.html" title="Last updated on Dec 8, 2021, 1:50 PM UTC (736a5f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/238/062b55c...736a5f7.html" title="Last updated on Dec 8, 2021, 1:50 PM UTC (736a5f7)">Diff</a>

Add Test Suite metadata

---

index.bs

fix #246
/cc @BruceDai
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/247.html" title="Last updated on Jan 7, 2022, 2:36 AM UTC (17000df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/247/7984e4e...huningxin:17000df.html" title="Last updated on Jan 7, 2022, 2:36 AM UTC (17000df)">Diff</a>

Fix a typo of softmax pseudo code

---

index.bs

In https://www.w3.org/2022/01/13-webmachinelearning-minutes.html#t06 it was suggested we add a real-time video processing use case. Here's a proposal for that.
A few questions:
- I put this in the "Framework Use Cases" section. Not a perfect fit but I wanted to differentiate from the "Application Use Cases" that in the context of this spec refer to various ML models. Maybe we can find a better name for the "Framework Use Cases" section?
- In this proposal, I did not explicitly define what makes up "the media pipeline" given the details of that are still WIP. Should we instead refer informatively the specs that we currently think will make up this pipeline and maintain this use case as our understanding evolves?

Add real-time video processing use case

---

index.bs

Include the dilation into the calculation.
fix #222
@wchao1115 @pyu10055 @anssiko , PTAL.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/232.html" title="Last updated on Nov 23, 2021, 6:58 AM UTC (483afef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/232/aaddda1...huningxin:483afef.html" title="Last updated on Nov 23, 2021, 6:58 AM UTC (483afef)">Diff</a>

Fix output size calculation of conv2d and convTranspose2d

---

index.bs

I started filling in a high-level description for the MLOperand that was missing referring to the programming model section for a more elaborate description. As a drive-by, I reworked the MLOperator description a bit to refer to the activation functions explicitly. Perhaps having this list here helps the readers? I hope it is not too hard to maintain if we add more activation functions.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/237.html" title="Last updated on Jan 17, 2022, 3:51 PM UTC (b08444a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/237/fd171b5...b08444a.html" title="Last updated on Jan 17, 2022, 3:51 PM UTC (b08444a)">Diff</a>

Add MLOperand and update MLOperator description

---

index.bs

- Define MLContext internal slots
- Migrate context type, device preference, power preference into MLContext
(prose sourced from WebIDL comments and device selection section)
- Define createContext() method steps in terms of MLContext internal slots
---
I took a stab at moving some WebIDL comments into prose, and on the same pass defined MLContext internal slots and tied those to the existing getContext() algorithm. This internal state may be useful also in other algorithms. There's probably room for improvement, so looking for your comments.
Please check in particular that the createContext() behaviour is as we'd like it to be (you can set either context, or device and power preference, not all at the same time).
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pu …

Update createContext() and MLContext interface prose and algorithms

---

index.bs

Fix #254
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/259.html" title="Last updated on Apr 4, 2022, 3:55 PM UTC (887eafc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/259/5b6913b...887eafc.html" title="Last updated on Apr 4, 2022, 3:55 PM UTC (887eafc)">Diff</a>

Add privacy considerations for cached/persisted data

---

index.bs

fix #268
@wchao1115 @anssiko @RafaelCintron , PTAL. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/273.html" title="Last updated on Jun 17, 2022, 3:59 AM UTC (669a86d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/273/e9b9e2c...huningxin:669a86d.html" title="Last updated on Jun 17, 2022, 3:59 AM UTC (669a86d)">Diff</a>

Drop WebGL interoperability

---

Makefile

Currently the bikeshed offline mode fails, since it's using the "die on everything" policy (see [bikeshed options](https://tabatkins.github.io/bikeshed/#cli-options)).
The bikeshed online mode uses forced mode, i.e. "die on nothing".
This small change uses "die on fatal" policy in offline mode, and keeps "die on nothing" for online mode.
The offline "die on nothing", i.e. forced mode is left in a comment.
Signed-off-by: Zoltan Kis <zoltan.kis@intel.com>

Fix Makefile for offline mode

---

index.bs

fix #279 
This is feature is not widely supported by target native ML APIs. Otherwise the implementation likely leads to higher latency for the 1st inference and shape change. A framework can still support dynamic-tensor in its own way, and it can build and compute WebNN graphs when the dynamic-tensor's sizes are known during model-inference time.
@wchao1115 @anssiko @yuhonglin @wacky6 @gramalingam @RafaelCintron , PTAL. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/281.html" title="Last updated on Aug 25, 2022, 4:30 AM UTC (8d16657)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/281/35c7a47...huningxin:8d16657.html" title="Last updated on Aug 25, 2022, 4:30 AM UTC (8d16657)">Diff</a>

Drop dynamic tensor support

---

index.bs

Fix #248
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/287.html" title="Last updated on Aug 30, 2022, 1:09 PM UTC (f0f576b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/287/ebf5da2...f0f576b.html" title="Last updated on Aug 30, 2022, 1:09 PM UTC (f0f576b)">Diff</a>

Fix split() code sample

---

index.bs

Separate this small fix from PR #274 . Please take a look.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/290.html" title="Last updated on Sep 5, 2022, 6:09 AM UTC (0df59a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/290/39951a0...huningxin:0df59a5.html" title="Last updated on Sep 5, 2022, 6:09 AM UTC (0df59a5)">Diff</a>

Fix a typo in softsign pseudo code

---

explainer.md

I happened to visit the explainer (it still reads well!) so I updated the comparison table while I was there, and fixed a few typos.

Update API comparison table for WebNN API and Model Loader API

---

explainer.md
index.bs

Fix #272 
According to the feedback of [WebML WG Teleconference – 16 June 2022](https://www.w3.org/2022/06/16-webmachinelearning-minutes.html#t06), this PR supports async context creation and [sync postfix propsoal](https://github.com/webmachinelearning/webnn/issues/272#issuecomment-1153394807) that is summarized in the following table:
| method | async | sync |
---|---|---
| create a context | `ML.createContext` | `ML.createContextSync` |
| build a graph | `MLGraphBuilder.build` | `MLGraphBuilder.buildSync` |
| compute a graph | `MLContext.compute` | `MLContext.computeSync` |
@wchao1115 @anssiko @dontcallmedom @RafaelCintron @yuhonglin @wacky6 , PTAL. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/274.html" title="Last updated on Aug 28, 2022, 8:41 AM UTC …

Support async context creation and use sync postfix

---

index.bs

This is to align with other W3C specification prose. Trivial merge.
Feel free to edit/add commits.
@huningxin @wchao1115
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/305.html" title="Last updated on Dec 1, 2022, 4:40 PM UTC (982fcd2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/305/29c0323...zolkis:982fcd2.html" title="Last updated on Dec 1, 2022, 4:40 PM UTC (982fcd2)">Diff</a>

Editorial: improve titles by including interface/method/dict etc.

---

index.bs

Cherry-picked from #301 to help reviewing.
It refers to (missing) steps for validating `MLContext`, which will be added in a separate PR.
It is marked as an issue.
@anssiko @wchao1115 @huningxin
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/309.html" title="Last updated on Dec 8, 2022, 4:14 PM UTC (7c606e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/309/8ac6b40...zolkis:7c606e2.html" title="Last updated on Dec 8, 2022, 4:14 PM UTC (7c606e2)">Diff</a>

Add constructor steps to MLGraphBuilder

---

index.bs

A trivial editorial change, just add correct referencing to "exist" clauses.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/313.html" title="Last updated on Dec 12, 2022, 7:09 PM UTC (f4a7f13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/313/8ac6b40...zolkis:f4a7f13.html" title="Last updated on Dec 12, 2022, 7:09 PM UTC (f4a7f13)">Diff</a>

Fix #311: use [=map/exist=] instead of exist

---

index.bs

Several small commits to improve the createContext() steps, and add the validate MLContext steps.
Fixes #308.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/310.html" title="Last updated on Dec 13, 2022, 5:35 PM UTC (fc8854c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/310/8ac6b40...zolkis:fc8854c.html" title="Last updated on Dec 13, 2022, 5:35 PM UTC (fc8854c)">Diff</a>

MlContext improvements

---

index.bs

A differential editorial change, in continuation of #310
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/315.html" title="Last updated on Dec 13, 2022, 6:48 PM UTC (866bb70)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/315/1a8de89...zolkis:866bb70.html" title="Last updated on Dec 13, 2022, 6:48 PM UTC (866bb70)">Diff</a>

Fix error handling

---

index.bs

The sizes option of resample2d specifies the target sizes for each spatial dimensions of input operand. Its type should be consistent with the type of operand dimensions which is unsigned long.
fix #300
@wchao1115 @anssiko @wacky6, PTAL.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/306.html" title="Last updated on Dec 5, 2022, 2:42 AM UTC (a91d79b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/306/64e2648...huningxin:a91d79b.html" title="Last updated on Dec 5, 2022, 2:42 AM UTC (a91d79b)">Diff</a>

Use unsigned long type for sizes option of resample2d

---

index.bs

Finally had a chance to do this. Adding `lstm` and `lstmCell` as additional operations in the spec. Since the addition of `gru` and `gruCell` there have been numerous questions about LSTM. As a widely popular recurrent network, supporting LSTM along with GRU is generally seen as important for API completeness. 
This change also made some editorial cleanups of existing wordings for GRU, and proposes a name change of the existing `MLOperator` to `MLActivation` to reflect its true purpose in the spec as a generic definition of an activation function i.e. not every operation can be an activation function, etc.
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/321.html" title="Last updated on Jan 9, 2023, 9:34 PM UTC (8545e28)">Preview</a> | <a …

Add LSTM to the operator list

---

explainer.md
index.bs

fix #318
@wchao1115 @anssiko @wacky6 @RafaelCintron , please take a look. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/323.html" title="Last updated on Jan 11, 2023, 7:13 AM UTC (a750ea4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/323/5a4e73e...huningxin:a750ea4.html" title="Last updated on Jan 11, 2023, 7:13 AM UTC (a750ea4)">Diff</a>

Transfer the input and output views for asynchronous execution

---

index.bs

MLGraph is a key concept in the spec that needs to be introduced early, since many things depend on them, for instance:
- syn/async execution algorithms in MLContext (in great detail)
- MLCommandEncoder initialization.
Also, MLCommandEncoder is related to WebGPU interoperability and execution, so it makes sense to be defined after [WebGPU Interoperability](https://webmachinelearning.github.io/webnn/#api-mlcontext-webgpu-interop) and nearer the execution algorithms.
I tried a lot of variations for where to put MLGraph, as ideally it has to be defined before the execution algorithms, but since MLContext should not be divided, it made sense to place it right before MLContext.
It is true MLGraph needs MLContext, but context was introduced in the ML interface, so it flows fine.
I think this …

Move the MLGraph and MLCommandEncoder sections up for cleaner read

---

index.bs

Fix #308: refer to MLContext validation steps from MLGraphBuilder constructor
Minor change, adds reference to missing algorithm.
@anssiko PTAL
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/332.html" title="Last updated on Jan 24, 2023, 9:56 AM UTC (6cefee4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/332/019a1f6...zolkis:6cefee4.html" title="Last updated on Jan 24, 2023, 9:56 AM UTC (6cefee4)">Diff</a>

Fix #308: refer to MLContext validation steps from MLGraphBuilder

---

index.bs

fix #345, #317
This PR makes the axis/axes definitions consistent by using the unsigned integer type and valid value range [0, N-1] where N is the tensor rank across the spec.
@wchao1115 @wacky6 @fdwr @anssiko @pyu10055 @RafaelCintron , PTAL. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/359.html" title="Last updated on Mar 4, 2023, 12:35 AM UTC (9781939)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/359/14c6670...huningxin:9781939.html" title="Last updated on Mar 4, 2023, 12:35 AM UTC (9781939)">Diff</a>

Use unsigned integer axis

---

index.bs

fix #354
@wchao1115 @wacky6 @anssiko @pyu10055 @RafaelCintron , PTAL. Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/355.html" title="Last updated on Mar 1, 2023, 2:00 AM UTC (91547d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/355/14c6670...huningxin:91547d4.html" title="Last updated on Mar 1, 2023, 2:00 AM UTC (91547d4)">Diff</a>

Use static padding values for `pad` operation

---

.github/workflows/auto-publish.yml
index.bs

Related #322
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/340.html" title="Last updated on Mar 31, 2023, 6:34 AM UTC (0a32c8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/340/00d3cdd...0a32c8c.html" title="Last updated on Mar 31, 2023, 6:34 AM UTC (0a32c8c)">Diff</a>

Add Status of this document note for Candidate Recommendation

---

index.bs

@huningxin @anssiko PTAL, thanks.
***
<a href="https://pr-preview.s3.amazonaws.com/BruceDai/webnn/pull/367.html" title="Last updated on Mar 23, 2023, 9:37 AM UTC (db53c2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/367/d3cc570...BruceDai:db53c2f.html" title="Last updated on Mar 23, 2023, 9:37 AM UTC (db53c2f)">Diff</a>

Update newShape with null value for reshape operation

---

index.bs

This PR is based on the discussion of #369 as the first step. It includes the changes:
1. Change `starts` and `sizes` parameters to be of a sequence of unsigned long.
2. Remove `MLSliceOptions.axes`.
The `MLSliceOptions.steps` may need more discussion and will be left to a separate PR.
Fix #369
@wchao1115 @anssiko @pyu10055 @wacky6 @fdwr, PTAL!
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/376.html" title="Last updated on Apr 13, 2023, 3:11 AM UTC (8efc568)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/376/47d64fc...huningxin:8efc568.html" title="Last updated on Apr 13, 2023, 3:11 AM UTC (8efc568)">Diff</a>

Simplify `slice` op

---

index.bs

Add the constant() algorithms.
This another take on how to specify polymorphic functions (compare that with clamp() in #348 
I like this approach more.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/365.html" title="Last updated on May 14, 2023, 7:26 PM UTC (dad23d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/365/b0fb131...zolkis:dad23d1.html" title="Last updated on May 14, 2023, 7:26 PM UTC (dad23d1)">Diff</a>

Add the constant() method steps.

---

index.bs

This is an update to the compatibility table to note the latest status of float16 per discussion in https://github.com/webmachinelearning/webnn/issues/373.
- Note TC39 Float16Array proposal is WIP
- Update issue links
(Bikeshed syntax not supported inside tables, thus plain HTML.)
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/386.html" title="Last updated on Jun 6, 2023, 9:08 AM UTC (af8e9c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/386/9774d49...af8e9c6.html" title="Last updated on Jun 6, 2023, 9:08 AM UTC (af8e9c6)">Diff</a>

Add float16 to MLOperandType and ArrayBufferView compatibility table

---

index.bs

Add the batch norm algorithm. 
Moved from #339 to the new [target branch](https://github.com/webmachinelearning/webnn/tree/zk-conventions-integration).
See all similar changes together with this one in a single context at https://zolkis.github.io/webnn/.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/397.html" title="Last updated on Jun 13, 2023, 7:51 PM UTC (0eea13e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/397/9774d49...zolkis:0eea13e.html" title="Last updated on Jun 13, 2023, 7:51 PM UTC (0eea13e)">Diff</a>

Add the batch normalization algorithm

---

index.bs

Moved from #366 
New target branch: https://github.com/webmachinelearning/webnn/tree/zk-conventions-integration
See all similar changes together with this one in a single context at https://zolkis.github.io/webnn/.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/398.html" title="Last updated on Jun 13, 2023, 7:50 PM UTC (2845074)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/398/c22a3ac...zolkis:2845074.html" title="Last updated on Jun 13, 2023, 7:50 PM UTC (2845074)">Diff</a>

Add algorithm to concat()

---

index.bs

Moved from #348 
New target branch.
See all similar changes together with this one in a single context at https://zolkis.github.io/webnn/.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/399.html" title="Last updated on Jun 13, 2023, 7:50 PM UTC (dc4d3d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/399/c22a3ac...zolkis:dc4d3d6.html" title="Last updated on Jun 13, 2023, 7:50 PM UTC (dc4d3d6)">Diff</a>

Clamp algorithm

---

index.bs

The fix is verified by the webnn-polyfill **lstm** and **lstmCell** implementations and tests: https://github.com/webmachinelearning/webnn-polyfill/pull/227.
@wchao1115 @fdwr @huningxin PTAL, thanks.
***
<a href="https://pr-preview.s3.amazonaws.com/BruceDai/webnn/pull/385.html" title="Last updated on May 22, 2023, 3:15 PM UTC (1732b82)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/385/c22a3ac...BruceDai:1732b82.html" title="Last updated on May 22, 2023, 3:15 PM UTC (1732b82)">Diff</a>

Fix typo error for lstm operations

---

index.bs

Remove extra parameter from 'create MLOperand' invocation.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/394.html" title="Last updated on Jun 2, 2023, 1:35 PM UTC (1f4dd64)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/394/c22a3ac...zolkis:1f4dd64.html" title="Last updated on Jun 2, 2023, 1:35 PM UTC (1f4dd64)">Diff</a>

Fix #393 for input()

---

index.bs

Several separate commits, targeting the style changes needed to hide large algorithms and examples, have stylistic frames for internal slots, etc.
First only style related changes, then adapted the existing changes in main, then applied indentation and fixed make errors.
Also needed to sync some fixes that have open PRs in the main branch.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/401.html" title="Last updated on Jun 19, 2023, 8:46 PM UTC (e260d9f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/401/9ad554d...zolkis:e260d9f.html" title="Last updated on Jun 19, 2023, 8:46 PM UTC (e260d9f)">Diff</a>

Add stylistic changes

---

index.bs

Using the improved platform specific steps developed for clamp(), update the algorithms defined so far: input, constant, clamp, concat, batch norm, and the create activation steps.
This is to figure out the best steps to be also applied to subsequent algorithms.
@huningxin PTAL
Because the main branch was also merged, a lot of commits appear here, but only this one is relevant:
https://github.com/webmachinelearning/webnn/pull/405/commits/8fac5ca49b10e2c5697b6dab871f0c5a25d2a877
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/405.html" title="Last updated on Jun 21, 2023, 6:05 PM UTC (963c9a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/405/329f41c...zolkis:963c9a0.html" title="Last updated on Jun 21, 2023, 6:05 PM UTC …

Align algorithms defined so far

---

index.bs

Add definitions to the `MLBufferResourceView` dictionary.
Add the build() section, containing the build() and buildSync() methods and their algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/406.html" title="Last updated on Jun 21, 2023, 7:08 PM UTC (6c6e033)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/406/c54d842...zolkis:6c6e033.html" title="Last updated on Jun 21, 2023, 7:08 PM UTC (6c6e033)">Diff</a>

Add the build() and buildSync() algorithms

---

index.bs

Add the conv2d and convTranspose2d algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/407.html" title="Last updated on Jun 21, 2023, 7:41 PM UTC (567396b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/407/c54d842...zolkis:567396b.html" title="Last updated on Jun 21, 2023, 7:41 PM UTC (567396b)">Diff</a>

Add the conv2d and convTranspose2d algorithms

---

index.bs

Add element-wise unary algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/409.html" title="Last updated on Jun 21, 2023, 8:09 PM UTC (0fab039)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/409/c54d842...zolkis:0fab039.html" title="Last updated on Jun 21, 2023, 8:09 PM UTC (0fab039)">Diff</a>

Add element-wise unary algorithms

---

index.bs

Add the linear function algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/417.html" title="Last updated on Jun 26, 2023, 12:57 PM UTC (5480f38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/417/c54d842...zolkis:5480f38.html" title="Last updated on Jun 26, 2023, 12:57 PM UTC (5480f38)">Diff</a>

Add the linear function algorithm

---

index.bs

Add the reduction algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/423.html" title="Last updated on Jun 26, 2023, 7:27 PM UTC (ea7ff6d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/423/c54d842...zolkis:ea7ff6d.html" title="Last updated on Jun 26, 2023, 7:27 PM UTC (ea7ff6d)">Diff</a>

Add the reduction algorithms

---

index.bs

Add the transpose algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/435.html" title="Last updated on Jun 27, 2023, 4:43 PM UTC (0f4e059)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/435/c54d842...zolkis:0f4e059.html" title="Last updated on Jun 27, 2023, 4:43 PM UTC (0f4e059)">Diff</a>

Add the transpose algorithm

---

index.bs

Add the prelu() algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/422.html" title="Last updated on Jun 29, 2023, 9:27 AM UTC (0d082e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/422/38c78f6...zolkis:0d082e5.html" title="Last updated on Jun 29, 2023, 9:27 AM UTC (0d082e5)">Diff</a>

Add the prelu() algorithm

---

index.bs

Add the resample2d() algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/425.html" title="Last updated on Jun 29, 2023, 9:15 AM UTC (81b35b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/425/c6711c3...zolkis:81b35b0.html" title="Last updated on Jun 29, 2023, 9:15 AM UTC (81b35b0)">Diff</a>

Add the resample2d() algorithm

---

index.bs

Add the softmax algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/429.html" title="Last updated on Jun 29, 2023, 9:21 AM UTC (44d13c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/429/c6711c3...zolkis:44d13c1.html" title="Last updated on Jun 29, 2023, 9:21 AM UTC (44d13c1)">Diff</a>

Add the softmax algorithm

---

index.bs

Fix #439 , and also fix the transpose op.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/441.html" title="Last updated on Jul 12, 2023, 4:35 PM UTC (b7eaee9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/441/567396b...zolkis:b7eaee9.html" title="Last updated on Jul 12, 2023, 4:35 PM UTC (b7eaee9)">Diff</a>

Fix #439: add missing conv2d() and convTranspose2d() validation steps

---

index.bs

A series of changes including:
- add collapsible stylistic boxes for algorithms and other stylistic improvements
- add missing algorithms
- some white space alignments
- consistent args and variable names across the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/446.html" title="Last updated on Aug 25, 2023, 8:45 AM UTC (c067b22)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/446/8e63e07...zolkis:c067b22.html" title="Last updated on Aug 25, 2023, 8:45 AM UTC (c067b22)">Diff</a>

Add missing algorithms, add stylistic improvements, update with spec conventions

---

index.bs

Issue #375. 
1. Add the following ops: `equal, lesser, greater, greaterOrEqual, lesserOrEqual, not, where, copy, sqrt, erf, expand, gather, layerNormalization, reduceArgMin, reduceArgMax, cast, triangular`
2. Remove `squeeze`
3. Add a `constant` overload that accepts `start, end, step`.
4. Add `shape` method in `MLOperand` for runtime tensor shape query.
5. Add new data type `int64` and `uint64` for `reduceArgMin` and `reduceArgMax`.
Notes:
- The proposed `identity` op is named `copy` to denote explicit action.
- The proposed `elementwiseIf` is named `where` to be consistent with PyTorch and ONNX.
- The proposed `triangularMatrix` is named `triangular` for brevity.
- `squeeze` is removed. Framework seeking `squeeze`, `unsqueeze`, `flatten` should just use `reshape`. See canonical …

Add support for operations needed for well-known transformers e.g. Segment Anything, Stable Diffusion, etc.

---

index.bs

* Missing spaces in "itthrows"
* "lensizeth" ("size" appearing in the middle of "length")
That said, definition of "bias" is a little sketchy: 
> An MLOperand. Specifies the 1-D tensor of the bias values whose size is equal to the size of the feature dimension of the input. For example, for an input tensor with nchw layout, the size is the value of input.[[descriptor]].dimensions[1].
"size is the value..." reads like it's trying to define size, so a link to Infra's list/size doesn't make sense. I think this is trying to say that the size of the passed bias (a 1-D tensor) must match the dimension of the input, but without phrasing it as normative behavior. 
Maybe this should just be:
> An MLOperand. Specifies the 1-D tensor of the bias values whose size is equal to …

Fix a handful of markdown glitches, probably c/o a find/replace.

---

.github/workflows/auto-publish.yml
index.bs

See https://github.com/w3c/spec-prod/blob/main/docs/options.md#build_fail_on
Fix #468
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 10, 2023, 1:56 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwebmachinelearning%2Fwebnn%2Fbf301f61224cb76ff4159fa143b002a13f3a4b1c%2Findex.bs&force=1&md-warning=not%20ready)
_If you don't have enough information above to solve the error by yourself (or to …

Define the Bikeshed build to fail on warnings

---

index.bs

A bunch of relatively stand-alone commits addressing issues noted in https://github.com/webmachinelearning/webnn/issues/450
It'll be easiest to review each individual commit as they're each a separate "topic". Reviewers should feel free to cherry-pick changes if anything is deemed controversial.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Dec 19, 2023, 6:48 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubuserconte …

Adopt Bikeshed best practices and Infra spec conventions

---

index.bs

Validation of the passed bias option only makes sense if the option is actually supplied. Correct the indentation for a few substeps.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 16, 2024, 8:42 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwebmachinelearning%2Fwebnn%2Fd5bee458649f3d6f8acf84fa64596d12a66a57e2%2Findex.bs&force=1&md-warning=not%20ready)
_If you don't have enough information …

Stylistic change: Fix indentation of steps validating bias option

---

index.bs

For #450
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 17, 2024, 5:47 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwebmachinelearning%2Fwebnn%2F69aeffa6d777f6a025f05a1edd028a6d3f9fe351%2Findex.bs&force=1&md-warning=not%20ready)
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an …

Stylistic change: Linkify MLOperandDataType enum members

---

index.bs

Just a missing "this" reference.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 17, 2024, 5:46 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwebmachinelearning%2Fwebnn%2F69aeffa6d777f6a025f05a1edd028a6d3f9fe351%2Findex.bs&force=1&md-warning=not%20ready)
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if …

Wording change: Add missing receiver when assigning to internal slot.

---

index.bs

The "validate buffer with descriptor given bufferView and descriptor" was validating that the type of the buffer was MLBufferView. This is not necessary, as all invokers (directly, and indirectly via "validate graph resources") only accept MLBufferViews via the WebIDL signatures.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 17, 2024, 5:35 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Finexora …

Wording change: Remove arg type test for internal validation algorithm

---

index.bs

`Die On: warning` metadata even if valid causes PR Preview to fail
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 18, 2024, 8:08 AM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwebmachinelearning%2Fwebnn%2Fd706febd9e1ffa166f1aaafaf193a71b29856bea%2Findex.bs&force=1&md-warning=not%20ready)
_If you don't have enough information above to solve the error by yourself (or to understand to which web …

Fix PR Preview

---

index.bs

As noted in issue #388, the reshape op build method currently supports a special null value in newShape array that instructs the implementation to compute the size of the dimension with the value null so that the total size remains constant. @fwdr proposed WebNN should only support the concrete values in newShape because this can be easily handled by framework through shape inference
It appears this change has already landed in the Chromium implementation and WPTs.
Fixes #388
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/505.html" title="Last updated on Jan 18, 2024, 6:49 PM UTC (ab36f0d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/505/50a00b9...inexorabletash:ab36f0d.html" title="Last updated on Jan 18, 2024, 6:49 PM …

Bug fix: Remove null value support in reshape()'s newShape parameter

---

index.bs

Bikeshed markdown requires the indentation to be at least 4 spaces.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/522.html" title="Last updated on Jan 19, 2024, 11:28 PM UTC (5f67a6d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/522/50a00b9...inexorabletash:5f67a6d.html" title="Last updated on Jan 19, 2024, 11:28 PM UTC (5f67a6d)">Diff</a>

Bug fix: Correct indentation of an iteration substep

---

index.bs

Infra convention and recommended by #211 - rather than the just «» syntax, specify the Infra type of "list" and link to the definition.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/515.html" title="Last updated on Jan 21, 2024, 1:37 AM UTC (7f0cd70)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/515/83262c6...inexorabletash:7f0cd70.html" title="Last updated on Jan 21, 2024, 1:37 AM UTC (7f0cd70)">Diff</a>

Wording change: Prefix literal lists with "the list"

---

index.bs

"Let ... be ..." is reserved for declaring variables.
For #450
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/517.html" title="Last updated on Jan 18, 2024, 5:59 PM UTC (c0c6507)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/517/50a00b9...inexorabletash:c0c6507.html" title="Last updated on Jan 18, 2024, 5:59 PM UTC (c0c6507)">Diff</a>

Wording change: Use Infra's "Set ... to ..." pattern for properties

---

index.bs

Simplify explicit link targets (e.g. power-preference-default) and link naming (e.g. default) with making the values scoped to a definition. Let Bikeshed take care of the linking, which also helps catch errors.
This PR layers on top of PR #495 since they touch similar lines, although they're conceptually separate. So only review the last commit here. Sorry about that!
This PR would also be partially obsoleted if we agree on #497 but it's harmless to merge as-is.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/499.html" title="Last updated on Jan 18, 2024, 6:51 PM UTC (b154e54)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/499/50a00b9...inexorabletash:b154e54.html" title="Last updated on Jan 18, 2024, 6:51 PM UTC …

Stylistic change: Replace some explicit use of link target naming with scopes

---

index.bs

Add new use cases:
- Text-to-image
- Speech Recognition
- Text Generation
- (Image Segmentation now refers to [SegAny] also)
Add new reference models:
- Text-to-image: stable-diffusion-v1-5
- Image segmentation: segment-anything
- Speech-to-text: whisper-tiny.en
- Text generation: t5-small, m2m100_418M, gpt2, llama-2-7b
Remove redundant local reference: [POWERFUL-FEATURES]
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/507.html" title="Last updated on Jan 18, 2024, 7:41 PM UTC (1d0f5c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/507/50a00b9...1d0f5c0.html" title="Last updated on Jan 18, 2024, 7:41 PM UTC (1d0f5c0)">Diff</a>

Revise use cases with transformers

---

.gitignore

`make` generates an `index.html` file which should not be uploaded to the repo
In another spec I worked on, this [resulted in the `index.html` file accidentally being uploaded](https://github.com/WICG/file-system-access/pull/398) (and no one noticed for a while, whoops). It would be nice to avoid that outcome here :)

Meta: Add a gitignore

---

index.bs

Bundle validation right into context creation, rather than making it a separate step.
Fixes #498
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/519.html" title="Last updated on Jan 25, 2024, 5:53 PM UTC (99ca098)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/519/7773794...inexorabletash:99ca098.html" title="Last updated on Jan 25, 2024, 5:53 PM UTC (99ca098)">Diff</a>

Wording change: Streamline context creation and validation algorithms

---

index.bs

This PR has two changes, and is submitted as two commits for ease of review, although it's a single "theme" so one PR:
1. Drop arg type assertions for methods defined by WebIDL. 
2. Convert internal algorithm type assertions into parameter types, following Infra conventions
For #455
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/518.html" title="Last updated on Jan 21, 2024, 1:40 AM UTC (252631b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/518/83262c6...inexorabletash:252631b.html" title="Last updated on Jan 21, 2024, 1:40 AM UTC (252631b)">Diff</a>

Wording change: Don't use asserts for validating argument types

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/521.html" title="Last updated on Jan 24, 2024, 8:13 PM UTC (a98a802)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/521/fa91851...inexorabletash:a98a802.html" title="Last updated on Jan 24, 2024, 8:13 PM UTC (a98a802)">Diff</a>

Wording change: Tidy up more arrays within algorithms to be lists

---

SpecCodingConventions.md
index.bs

Some uses of "for each" in algorithms were linking to the map iteration definition in Infra. Fix this to point at the list iteration definition. Today I learned: this applies to iteration over ranges too!
Also updated coding conventions to cover these cases.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/527.html" title="Last updated on Jan 24, 2024, 8:07 PM UTC (dd5f9a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/527/fa91851...inexorabletash:dd5f9a0.html" title="Last updated on Jan 24, 2024, 8:07 PM UTC (dd5f9a0)">Diff</a>

Bug fix: Correct linking for list/range iterations

---

index.bs

* Per #395 make it clearer that the algorithm is working on a new descriptor (a copy of the input's)
* When invoking the algorithm, pass the required input argument.
* Rename algorithm from "resample output sizes" to "calculate resample output sizes" which more clearly descripts what is happening and aligns with similar algorithms in the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/520.html" title="Last updated on Jan 24, 2024, 8:20 PM UTC (111172a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/520/fa91851...inexorabletash:111172a.html" title="Last updated on Jan 24, 2024, 8:20 PM UTC (111172a)">Diff</a>

Bug fix: resample2d output size calculation algorithm and usage

---

index.bs

The default linking for [=object=] is to FileAPI's blob URL entry object member[1], which is definitely wrong.
Replace such references with:
* Infra's ordered map[2], when a dictionary is intended, as that's what a JavaScript object is translated into via bindings.
* Links to new definitions for "platform operator" and "platform operand" which include the "implementation-defined" phrase so links to the terms can be greatly simplified. These definitions should be further expanded to include "connect", "input" and "output" but that can be tackled later.
This reduces the number of "implementation-defined" phrases to just a handful in the spec, which helps with #462.
[1] https://www.w3.org/TR/FileAPI/#blob-url-entry-object
[2] https://infra.spec.whatwg.org/#ordered-map
***
[PR …

Wording change: drop links to File API's "object", define platform operand/operator 

---

index.bs

Replace definitions for MLContext's device type and power preference which are used internally only, with the identical WebIDL-defined MLDeviceType and MLPowerPreference enums.
Fixes #497
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/535.html" title="Last updated on Jan 27, 2024, 6:53 PM UTC (8353c46)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/535/479ce17...inexorabletash:8353c46.html" title="Last updated on Jan 27, 2024, 6:53 PM UTC (8353c46)">Diff</a>

Wording change: Define power prefs & device type using WebIDL enums

---

SpecCodingConventions.md
index.bs

Bikeshed automatically annotates dictionary members with types and defaults, so repeating that in the prose is extra work and extra noise. Remove both and reword as needed. For #483
Also:
- Simplify text by removing "Specifies" from most definition prose.
- Replace "sequence" with "list" in prose.
- Consistently give list member definitions using `*[ ... ]*` styling.
- Document the above in coding conventions.
This probably merits some discussion, so uploading early for comments.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/526.html" title="Last updated on Feb 4, 2024, 4:54 PM UTC (1a340fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/526/7ec2e18...inexorabletash:1a340fd.html" title="Last updated on Feb 4, 2024, 4:54 PM …

Wording change: Dedupe dictionary member type and default definitions

---

index.bs

Note that this isn't TypeScript or C++ - we are free to make the type annotations more specific, easier to read, etc. So there may be cases where we don't simply give an Infra or Web IDL type or rigorously follow the Infra style. Comments and suggestions welcome!
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/536.html" title="Last updated on Jan 27, 2024, 6:57 PM UTC (7cc1a6e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/536/479ce17...inexorabletash:7cc1a6e.html" title="Last updated on Jan 27, 2024, 6:57 PM UTC (7cc1a6e)">Diff</a>

Wording change: Add types to all internal algorithm members

---

index.bs

The algorithm and internal slot boxes had hard-coded CSS background colors set which didn't adjust when the page was viewed in dark mode.
They are simply removed as they don't seem necessary.
***
<a href="https://pr-preview.s3.amazonaws.com/reillyeon/webnn/pull/557.html" title="Last updated on Feb 6, 2024, 6:38 PM UTC (ee958c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/557/c9d2dd7...reillyeon:ee958c0.html" title="Last updated on Feb 6, 2024, 6:38 PM UTC (ee958c0)">Diff</a>

Remove hard-coded colors which break dark mode

---

index.bs

A step comparing data types didn't specify where one of the types was coming from. Oops!
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/558.html" title="Last updated on Feb 6, 2024, 6:55 PM UTC (8a00b50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/558/c9d2dd7...inexorabletash:8a00b50.html" title="Last updated on Feb 6, 2024, 6:55 PM UTC (8a00b50)">Diff</a>

Bug fix: Missing variable name in conv2d

---

index.bs

Bikeshed is already inferring the correct links, but map the scope of the slots explicit for consistency.
Already covered in SpecCodingConventions.md
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/556.html" title="Last updated on Feb 6, 2024, 6:13 PM UTC (5520160)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/556/c9d2dd7...inexorabletash:5520160.html" title="Last updated on Feb 6, 2024, 6:13 PM UTC (5520160)">Diff</a>

Style change: Scope the links for MLContext internal slots

---

index.bs

Fixes #528
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/546.html" title="Last updated on Feb 8, 2024, 2:43 AM UTC (2bf3bd7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/546/d1a02f2...a-sully:2bf3bd7.html" title="Last updated on Feb 8, 2024, 2:43 AM UTC (2bf3bd7)">Diff</a>

Remove MLCommandEncoder

---

index.bs

MLArgMinMaxOptions and MLReduceOptions have an 'axes' member that the IDL declares as defaulting to null. They have type sequence<unsigned long> which is not nullable. The intent is that these are optional members with default behavior if not present, which is handled in the algorithm already.
If the desire is to be able to explicitly pass null, the IDL fix would be to make the type nullable: `sequence<unsigned long>? axes = null;` but that's inconsistent with the rest of the spec and not the convention for optional dictionary members.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/539.html" title="Last updated on Feb 7, 2024, 5:43 PM UTC (44d5e0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/539/d1a02f2...inexorabletash:4 …

Bug fix: Optional sequences shouldn't be defaulted to null

---

index.bs

Fixes #494 which has the text and example. I added the validation step which matches the webnn-baseline impl referenced therein.
* "2-D" seems to be used more commonly than "2D" in the spec
* "batches" doesn't seem to be rigorously defined - room for future improvement here and in matmul?
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/550.html" title="Last updated on Feb 7, 2024, 5:43 PM UTC (3cef040)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/550/d1a02f2...inexorabletash:3cef040.html" title="Last updated on Feb 7, 2024, 5:43 PM UTC (3cef040)">Diff</a>

Content: The input of triangular should be at least 2D tensor

---

index.bs

This adds an explicit algorithm step in layerNormalization() to provide a default described only in prose for the axes option.
For #211
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/538.html" title="Last updated on Feb 10, 2024, 2:11 AM UTC (b6c8489)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/538/d1a02f2...inexorabletash:b6c8489.html" title="Last updated on Feb 10, 2024, 2:11 AM UTC (b6c8489)">Diff</a>

Bug fix: Provide default for MLLayerNormalizationOptions axes in steps

---

index.bs

- No 'dfn' refs found for 'rank-'
- No 'idl' refs found for 'MLCommandEncoder'
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/564.html" title="Last updated on Feb 12, 2024, 10:52 AM UTC (6b3c637)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/564/e3f32fe...6b3c637.html" title="Last updated on Feb 12, 2024, 10:52 AM UTC (6b3c637)">Diff</a>

Fix Bikeshed build errors

---

index.bs

This change introduces a new section for Algorithms, following APIs, to collect algorithms referenced throughout the specification.
A section for Broadcasting is introduced, which defines broadcasting shapes and gives an explicit algorithm matching WebNN implementations of NumPy's General Broadcasting Rules. Definitions for "broadcastable" and "unidirectionally broadcastable" are introduced. The previous definition of "broadcast-shapes" is removed in favor of these new algorithms.
For #324, #462, and potentially #523.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/534.html" title="Last updated on Feb 13, 2024, 4:40 AM UTC (145bff1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/534/55183f7...inexorabletash:145bff1.html" …

New content: Add definition for shape broadcasting

---

index.bs

This status text is a high-level summary for busy people.
- Implementation experience update
- Significant new & removed features, use cases, conventions update
- Significant new features in development, MLBuffer
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/532.html" title="Last updated on Feb 13, 2024, 9:09 AM UTC (8e0fff4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/532/a26b587...8e0fff4.html" title="Last updated on Feb 13, 2024, 9:09 AM UTC (8e0fff4)">Diff</a>

Update Status of this document for CR Snapshot

---

index.bs

Simplify text that digs the dimensions and dataType out of an MLOperand's [[descriptor]] by introducing definitions, and use them consistently.
Also simplify the definition for MLOperand's rank, and use it in more places.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/555.html" title="Last updated on Feb 13, 2024, 7:07 PM UTC (ef7355e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/555/d48e394...inexorabletash:ef7355e.html" title="Last updated on Feb 13, 2024, 7:07 PM UTC (ef7355e)">Diff</a>

Content change: Add definitions for MLOperand's shape and dataType

---

index.bs

For gemm() - make lists that are mutated be explicit clones using Infra terminology, and simplify the wording reversing the lists.
For matmul() - make lists that are mutated be explicit clones using Infra terminology, use append/prepend definitions from Infra, convert a variable change from "let" to "set" and drop use of "array".
For #395
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/523.html" title="Last updated on Feb 14, 2024, 6:39 AM UTC (9deaeb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/523/8503e24...inexorabletash:9deaeb5.html" title="Last updated on Feb 14, 2024, 6:39 AM UTC (9deaeb5)">Diff</a>

Wording change: Tighten up output shape calculation algorithms

---

index.bs

Remove the definition and algorithm steps for
- ML.createContextSync()
- MLGraphBuilder.buildSync()
- MLContext.computeSync()
This PR also removes the synchronous execution description from Programming Model section.
The previous algorithm steps of `MLGraphBuilder.build()` depends on `MLGraphBuilder.buildSync()`. The algorithm steps of `MLGraphBuilder.buildSync()` have issue tracked by #457. That is left to a separate PR. This PR just merges the algorithm steps of `MLGraphBuilder.buildSync()` into `MLGraphBuilder.build()` with some modifications:
- Remove "The permissions and context validity have been checked..." note regarding to #501.
- Change throwing exception to rejecting the promise with exception.
Fix #531
@wchao1115 @anssiko @inexorabletash , PTAL. Thanks!
***
<a …

Drop the support of synchronous execution

---

index.bs

Follow-up to #546. `MLBufferResourceView` is not relevant without `MLCommandEncoder`
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/553.html" title="Last updated on Feb 8, 2024, 2:41 AM UTC (66588cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/553/d1a02f2...a-sully:66588cf.html" title="Last updated on Feb 8, 2024, 2:41 AM UTC (66588cf)">Diff</a>

Remove MLBufferResourceView

---

docs/IssueTriage.md

Introduces label links to:
- Help readers get to issues directly
- Add visual cues (links render as colorful pills)

Update Triage Guidance

---

docs/SpecCodingConventions.md
index.bs

Replace `&rarr;` with → and document this preference.
Really, really minor editorial change. I think the use of `&rarr;` was my fault.
When #506 is resolved, we should document the outcome as well.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/570.html" title="Last updated on Feb 15, 2024, 7:14 PM UTC (ccce939)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/570/c4c369a...inexorabletash:ccce939.html" title="Last updated on Feb 15, 2024, 7:14 PM UTC (ccce939)">Diff</a>

Style: Prefer characters to entities

---

index.bs

For operations defined in bulk - argMin/argMax, element-wise binary, unary, and logical ops, plus pooling and reduction ops - make the styling consistent:
- A single `<div class=algorithm-steps>` around all definitions
- A separate `<div algorithm>` around each op's steps.
This was already done for the element-wise ops so already the majority style. Pooling ops now have just a single "Algorithm" watermark (instead of 3), and argMin/argMax and reduction ops now have a watermark instead of none.
For #450
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/576.html" title="Last updated on Feb 21, 2024, 5:27 PM UTC (b57760b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/576/4ad9a63...inexorabletash:b57760b.html" title="Last updated …

Style: Make grouped algorithm steps consistent

---

index.bs

- Validate that inputs is non-empty, present in the Chromium prototype implementation.
- Add local "first" variable, to simplify steps.
- Drop assertion about dataTypes being the same, already covered by the algorithm.
- Add step validating that the ranks are the same, present in the Chromium prototype implementation, and drop the assertion.
- Make output descriptor creation more explicit.
- Drop "If any of the following steps fail" since the steps explicitly threw already.
- Init desc.dimensions[axis] from "first" and start loop at 1.
Fixes #503
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/577.html" title="Last updated on Feb 21, 2024, 6:15 PM UTC (4b3f05e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/577/4ad9a63...inex …

Bug fix: Make concat() validation and initialization more precise.

---

index.bs

The method steps check an operand's data type, which should not be done by invoking a method (because side effects) but by looking at the internal state.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/578.html" title="Last updated on Feb 21, 2024, 6:29 PM UTC (8e42d1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/578/4ad9a63...inexorabletash:8e42d1f.html" title="Last updated on Feb 21, 2024, 6:29 PM UTC (8e42d1f)">Diff</a>

Bug fix: gather() steps shouldn't invoke methods

---

index.bs

Fixes #560
Follow-up to #553
To be coordinated with corresponding changes to the Model Loader API spec: https://github.com/webmachinelearning/model-loader/pull/43
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/569.html" title="Last updated on Feb 15, 2024, 4:53 PM UTC (f205ed1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/569/745ddbc...a-sully:f205ed1.html" title="Last updated on Feb 15, 2024, 4:53 PM UTC (f205ed1)">Diff</a>

Remove MLBufferView

---

index.bs

By default, Bikeshed will resolve unscoped autolinks to definitions _with_ a `for` value automatically if it can. Turning this option on makes unscoped links only resolve to definitions _without_ a `for`, i.e. top-level definitions. Since we want to scope links (already called out in docs/SpecCodingConventions.md), turning this option on reveals where we're not scoping links.
Docs: https://speced.github.io/bikeshed/#metadata-assume-explicit-for
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/580.html" title="Last updated on Feb 22, 2024, 1:25 AM UTC (0c3c618)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/580/494d930...inexorabletash:0c3c618.html" title="Last updated on Feb 22, 2024, 1:25 AM UTC (0c3c618)">Diff</a>

Style: Turn on "Assume Explicit For" and scope autolinks

---

index.bs

Just a missing `}}`
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/581.html" title="Last updated on Feb 22, 2024, 8:50 PM UTC (43d2e1e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/581/a6326c0...inexorabletash:43d2e1e.html" title="Last updated on Feb 22, 2024, 8:50 PM UTC (43d2e1e)">Diff</a>

Bug fix: Correct an unclosed autolink 

---

index.bs

This covers:
* Reduction ops (including argMin/argMax)
* conv2d
* convTranspose2d
* Pooling ops (which rely on conv2d)
Fixes #500
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/582.html" title="Last updated on Feb 27, 2024, 9:51 PM UTC (2f9868c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/582/f269174...inexorabletash:2f9868c.html" title="Last updated on Feb 27, 2024, 9:51 PM UTC (2f9868c)">Diff</a>

Content: Specify output size calculations

---

index.bs

- Collapse partials for MLOperand and MLContext
- Move MLOperand and MLActivation up above MLGraphBuilder
- Move MLGraphBuilder's input, constant and build up near interface
- Tweak a couple of section titles
Fixes #579
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/586.html" title="Last updated on Feb 27, 2024, 6:37 PM UTC (e89d6d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/586/a904425...inexorabletash:e89d6d1.html" title="Last updated on Feb 27, 2024, 6:37 PM UTC (e89d6d1)">Diff</a>

Style: Only use partial interfaces for MLGraphBuilder

---

index.bs

This PR removes all uses of `DataError` from the spec in favor of using `TypeError` for all input validation
Notably, all validation checks and output shape calculations related to operand axes/ranks/dimensions/shapes are treated as `TypeError` with the rationale that axes/ranks/dimensions/shapes do not constitute an operand's _data_, but its _type_ ([as C++ does, for example](https://godbolt.org/z/5hW9fT7sY))
Fixes #583
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/589.html" title="Last updated on Mar 1, 2024, 12:38 AM UTC (f5abd8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/589/0de084d...a-sully:f5abd8c.html" title="Last updated on Mar 1, 2024, 12:38 AM UTC (f5abd8c)">Diff</a>

Throw TypeError for all input validation

---

index.bs

- Use a more common phrasing for "in parallel" steps.
- Make "in parallel" operations interact with script via queued tasks.
- Define an "ml task source" used for queued tasks.
- Ensure the correct Realm is used for asynch construction.
Relevant requirements/examples:
- https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel
- https://webidl.spec.whatwg.org/#js-promise-examples
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/593.html" title="Last updated on Mar 5, 2024, 8:24 PM UTC (8510ffc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/593/ca0b903...inexorabletash:8510ffc.html" title="Last updated on Mar 5, 2024, 8:24 PM UTC (8510ffc)">Diff</a>

Define task source, construct with realms, improve parallel usage

---

index.bs

Fix https://github.com/webmachinelearning/webnn/issues/595 .
After dropping the support of synchronous execution in https://github.com/webmachinelearning/webnn/issues/531 , we'd better to update the anchor link of `compute()` from `https://www.w3.org/TR/webnn/#api-mlcontext-async-execution` to `https://www.w3.org/TR/webnn/#api-mlcontext-compute` .
***
<a href="https://pr-preview.s3.amazonaws.com/ibelem/webnn/pull/596.html" title="Last updated on Mar 7, 2024, 4:07 AM UTC (c01e4c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/596/480b094...ibelem:c01e4c1.html" title="Last updated on Mar 7, 2024, 4:07 AM UTC (c01e4c1)">Diff</a>

Update anchor link for compute() after dropping synchronous execution support

---

index.bs

- in *check resample options*, remove a duplicate word
- in *expand()*, don't use two names for the same variable
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/597.html" title="Last updated on Mar 7, 2024, 8:14 PM UTC (1842a20)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/597/86081aa...inexorabletash:1842a20.html" title="Last updated on Mar 7, 2024, 8:14 PM UTC (1842a20)">Diff</a>

Bugfix: Duplicate word, variable name consistency

---

index.bs

Per #388, the change #505 removed null value support in reshape()'s newShape parameter. That pull request missed updating the prose description to match.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/601.html" title="Last updated on Mar 13, 2024, 7:36 PM UTC (360cc2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/601/1d1b531...inexorabletash:360cc2f.html" title="Last updated on Mar 13, 2024, 7:36 PM UTC (360cc2f)">Diff</a>

reshape(): Remove "nullable" in prose description of newShape

---

index.bs

* Bikeshed styles W3C spec substeps (and sub-substeps, etc) with bars to make the indentation level clearer. The explicit markup used for `class=algorithm-steps` was preventing the selector from matching. Simplify the markup and CSS to get *more* by doing *less*.
* The default `<summary>` element style is bold, which was making the specific definition within an algorithm's intro difficult to see. Override this for algorithms, so that the defined algorithm name "pops" more.
* Recently introduced broadcast algorithms weren't using the `<details>` / `<summary>` markup. Apply this to match the rest of the spec.
* Remove now-unused CSS `validusage` and `informalsteps` styling.
No content changes.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/594.html" title="Last …

Styles: simplify algorithm markup, improve step & dfn visibility

---

index.bs

Explicit steps were missing. Fill them in, following the precedent of lstm().
Also, fix a reference to a non-initialized variable in one branch within the lstm() steps.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/600.html" title="Last updated on Mar 14, 2024, 4:54 AM UTC (c38746c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/600/1d1b531...inexorabletash:c38746c.html" title="Last updated on Mar 14, 2024, 4:54 AM UTC (c38746c)">Diff</a>

Content: Define output for gru()

---

index.bs

The shape calculation for argMin/argMax and reduction ops is now fully specified, but the implied behavior of {axes:[]} for these ops and layerNormalization was not particularly clear.
Add a little text to make it clearer.
Fixes #493
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/599.html" title="Last updated on Mar 13, 2024, 4:31 PM UTC (48fab65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/599/1d1b531...inexorabletash:48fab65.html" title="Last updated on Mar 13, 2024, 4:31 PM UTC (48fab65)">Diff</a>

Content: Clarify the expected behavior for axes being empty

---

index.bs

- Adds validation that passed outputs are neither inputs nor constants, matching the Chromium implementation.
- Traverses the graph, starting with outputs, to visit all connected operands.
- Previously the outputs were iterated over to process inputs and constants, which didn't make any sense. Inputs are hooked up to [[inputsDescriptors]]. Nothing is specifically mentioned about constants, but an issue about transferring is referenced. (#566)
- The impact of MLGraphBuilder re-use (#567) is called out, since it could allow for removing the graph traversal.
- Populates graph's [[outputDescriptors]], which was previously just missing. (#448)
- Makes most of the validation behavior of build() happen synchronously rather than "in parallel". A promise is still returned, of course.
- Converting …

Content: Define build() steps more rigorously

---

index.bs

Several input MLOperands and sequence<MLActivations> were missed in 1d1b531a. Add 'em!
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/609.html" title="Last updated on Mar 21, 2024, 1:29 AM UTC (3f84969)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/609/1062297...inexorabletash:3f84969.html" title="Last updated on Mar 21, 2024, 1:29 AM UTC (3f84969)">Diff</a>

Bugfix: Add missing input operands and activations

---

index.bs

This fell out of making build() more specific - these terms are no longer needed, and the makeup of the MLGraph can be described more abstractly.
Discussed here: https://github.com/webmachinelearning/webnn/pull/603#pullrequestreview-1939733168
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/606.html" title="Last updated on Mar 18, 2024, 4:18 PM UTC (cfb8733)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/606/1062297...inexorabletash:cfb8733.html" title="Last updated on Mar 18, 2024, 4:18 PM UTC (cfb8733)">Diff</a>

Drop definitions for "platform operator" and "platform operand"

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/BruceDai/webnn/pull/611.html" title="Last updated on Mar 21, 2024, 6:13 AM UTC (0c0816e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/611/1062297...BruceDai:0c0816e.html" title="Last updated on Mar 21, 2024, 6:13 AM UTC (0c0816e)">Diff</a>

Bugfix: Updated the step of calculating output sizes by scales for resample2d

---

index.bs

The changes for conv2d include:
1. The channels of output shape should be set to output channels of filter operand
1. The groups should be validated with input channels.
1. The bias shape[0] should be equal to output channels.
1. The bias should be added into operator's inputs if it presents.
The changes for convTranspose2d include:
1. The channels of output shape should be set to the result of filter output channels of filter operand * groups.
1. The input channels of input operand should be equal to input channels of filter operand.
1. The bias shape[0] should be equal to output channels.
1. The bias should be added into operator's inputs if it presents.
1. The options.outputSizes should not be smaller than strides.
1. The output sizes should be set to options.outputSizes if it is …

BugFix: Fix algorithm steps of conv2d and convTranspose2d

---

index.bs

The "create an MLActivation" steps don't throw, so there's no need to re-throw.
Also, nothing specifies _init-steps_ so drop those, and simplify how the steps handle _options_, to align with how things are done for `MLOperands`. 
Discussed in https://github.com/webmachinelearning/webnn/pull/591#issuecomment-1970013201
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/619.html" title="Last updated on Mar 23, 2024, 6:37 PM UTC (c6ee63a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/619/91cb734...inexorabletash:c6ee63a.html" title="Last updated on Mar 23, 2024, 6:37 PM UTC (c6ee63a)">Diff</a>

Bugfix: Drop "re-throw" in MLActivation creation steps

---

index.bs

A smattering of methods on MLGraphBuilder (build, buildSync, concat, constant, expand, and input) had a note about permissions and context validity at the start of the steps. This is implicit, and applies to all methods so it was confusing - was there something special about these methods?
Nope. So remove the notes.
Fixes #501
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/620.html" title="Last updated on Mar 26, 2024, 5:49 PM UTC (af931d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/620/2f32429...inexorabletash:af931d2.html" title="Last updated on Mar 26, 2024, 5:49 PM UTC (af931d2)">Diff</a>

Bug fix: Drop "... have been checked..." notes

---

docs/SpecCodingConventions.md
index.bs

Document and apply these new conventions:
* Word-wrap IDL methods to prevent scrollbars
* Use * not ×, / not ÷, etc. Fixes #506
Apply these existing conventions:
* Prefer "foo's bar" to "the bar of foo"
* Make `nchw` link to enum definition (missed in a2866a50)
And these really minor cleanups
* Fix ASCII art diagram indentation (glitched in 75925de4)
* Remove double colons in "Returns::"
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/618.html" title="Last updated on Mar 22, 2024, 10:03 PM UTC (6fa9bf0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/618/91cb734...inexorabletash:6fa9bf0.html" title="Last updated on Mar 22, 2024, 10:03 PM UTC (6fa9bf0)">Diff</a>

Conventions: Add and apply a few more spec coding conventions

---

docs/SpecCodingConventions.md
index.bs

- Documents the convention.
- Dedupes `MLEluOptions`'s `alpha` definitions
- Dedupes `MLClampOptions`'s `minValue` and `maxValue`, and references #396
- Moves `MLOperandDescriptor` member documentation out of IDL comments
- Introduces simple definitions for `MLComputeResult`'s `inputs` and `outputs`
- Converts "device type" and "power preference" into definitions for `MLContextOptions`'s `deviceType` and `powerPreference`.
Also includes these adjacent changes to improve the document flow:
- Moves the "context type" definition into the `MLContext` section.
- Moves the Permission Policy Integration section from API into Programming Model which seems like a slightly better home for it.
Fixes #483
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/621.html" title="Last …

Conventions: Ensure all dict members have definitions

---

docs/SpecCodingConventions.md
index.bs

Fixes #588
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/627.html" title="Last updated on Apr 1, 2024, 4:37 PM UTC (f4535ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/627/60b8e0a...inexorabletash:f4535ca.html" title="Last updated on Apr 1, 2024, 4:37 PM UTC (f4535ca)">Diff</a>

Conventions: Use "rank" for variable names, when appropriate

---

index.bs

As of https://github.com/whatwg/webidl/issues/1310 Web IDL has Float16Array listed alongside the other typed array types. For WebNN we can now just defer to Web IDL for the link now.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/640.html" title="Last updated on Apr 10, 2024, 4:43 PM UTC (18fae72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/640/1f60107...inexorabletash:18fae72.html" title="Last updated on Apr 10, 2024, 4:43 PM UTC (18fae72)">Diff</a>

Float16Array has landed in Web IDL - remove workarounds

---

index.bs

As noted in #209, not all frameworks/platform APIs support all reduce operations, but these are easily emulated.
Decompositions are provided using the standard phrasing and style currently used throughout the spec. In the future, we may alter the wording to explicitly state that these decompositions can be used as templates for implementations to follow when their underlying frameworks/platform APIs do not support the operations.
Fixes #209
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/637.html" title="Last updated on Apr 6, 2024, 1:53 PM UTC (9469d7d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/637/1f60107...inexorabletash:9469d7d.html" title="Last updated on Apr 6, 2024, 1:53 PM UTC (9469d7d)">Diff</a>

Decompositions for reduceLogSum, reduceLogSumExp, and reduceSumSquare

---

index.bs

Certain operands like reshape2d() calculate dimensions in their output shape with expressions like shape[i] * scales[i] which could be larger than can be represented as a dimension in MLOperandDescriptor.
Introduce a "valid dimension" term, use it when calculating output dimensions in the following ops, and throw if needed.
- constant() (sequential fill)
- concat()
- conv2d()
- convTranspose2d()
- pad()
- pooling operators
- resample2d()
- reshape()
Fixes #610
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/641.html" title="Last updated on Apr 16, 2024, 3:44 AM UTC (67027f2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/641/1f60107...inexorabletash:67027f2.html" title="Last updated on Apr 16, 2024, 3:44 AM UTC …

Introduce "valid dimension", used as needed when calculating operand shapes

---

index.bs

Fix #634
/cc @a-sully
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/639.html" title="Last updated on Apr 8, 2024, 6:01 AM UTC (a2560c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/639/2f32429...huningxin:a2560c3.html" title="Last updated on Apr 8, 2024, 6:01 AM UTC (a2560c3)">Diff</a>

BugFix: `compute()` explicitly rejects a promise if buffer transferring fails

---

index.bs

Many complex operations in the spec are given decompositions, showing how the operation could be replaced through the use of more primitive operations. This text is repeated in many places. Improve this in two ways:
* Use Bikeshed's Text Macro[1] to reduce the repetition.
* Streamline the text, and make it explicit that if the underlying platform doesn't support an operation, WebNN API implementations can use the decomposition as a guide to emulate it.
The macro [EMULATED] is used at the end of an intro sentence since there are variations - some of the decompositions are grouped, and some make assumptions (e.g. activation functions, layouts, etc).
If we assume that implementations must implement all operations in the spec, either via the underlying platform or emulation, this fixes #187 …

Editorial: Make "generically emulated" text a macro, update wording

---

index.bs

`compute()` calls validate graph resources with the passed input/output maps and the graph's input/output descriptors. The intent is to ensure that all of a graph's descriptors are matched to a passed resource. However, the steps were only validating that a passed resource had a corresponding descriptor - it wouldn't flag if a resource was missing!
The Chromium prototype implementation made the test reflexive - all resources much have matching descriptors and vice versa. After deliberation we settled on a more helpful behavior: all inputs must be provided, but extra inputs are ignored. A requested output must be present, but dropping outputs is allowed. 
Fixes #602
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/622.html" title="Last updated on Apr 16, 2024, …

Revise graph resource validation

---

index.bs

When outputShapes is not specified, the output padding must be smaller than the stride along the same dimension.
This matches the Chromium prototype implementation.
Fixes #630
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/631.html" title="Last updated on Apr 2, 2024, 5:23 PM UTC (7c342d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/631/60b8e0a...inexorabletash:7c342d8.html" title="Last updated on Apr 2, 2024, 5:23 PM UTC (7c342d8)">Diff</a>

Validate restriction of output padding in convTranspose2d

---

README.md
index.bs

* #486 points out that indices can't be validated at build-time, and clamping behavior with an implementation note is given instead.
* Fix a typo in the steps.
* Replace several map-like iterations over lists with list iteration.
* #484 discusses support for negative indices. Added a note that if the underlying platform doesn't support them, the implementation can "polyfill" this with some additional logic.
Fixes #486
Fixes #484
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/642.html" title="Last updated on Apr 16, 2024, 4:04 PM UTC (cc0cf8a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/642/05b15b1...inexorabletash:cc0cf8a.html" title="Last updated on Apr 16, 2024, 4:04 PM UTC (cc0cf8a)">Diff</a>

gather(): Address indices validation and other algorithm nits

---

index.bs

Add a note based on @fdwr's comment: if the backend doesn't support a keepDimensions option, the implementation can insert a no-op reshape to keep or drop the reduced dimension(s) as needed.
Fixes #465
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/648.html" title="Last updated on Apr 18, 2024, 7:56 PM UTC (9beb397)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/648/26982c4...inexorabletash:9beb397.html" title="Last updated on Apr 18, 2024, 7:56 PM UTC (9beb397)">Diff</a>

Editorial: Add note about keepDimensions of reduction ops

---

index.bs

Fixes #645
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/651.html" title="Last updated on Apr 22, 2024, 5:49 PM UTC (6a158b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/651/50fbb92...a-sully:6a158b4.html" title="Last updated on Apr 22, 2024, 5:49 PM UTC (6a158b4)">Diff</a>

Remove softplus() steepness option

---

index.bs

- In gru(), batchSize and numDirections were used without being defined. Define them.
- In lstm(), numDirections was initialized to 2 if the direction was "backward", should be 1.
- In gru() and gruCell(), options.activations was unconditionally added to the operator. Make this conditional.
- In lstm() and lstmCell(), options.activations were not added to the operator. Add if given.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/655.html" title="Last updated on Apr 24, 2024, 7:04 PM UTC (1661bf9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/655/2d06961...inexorabletash:1661bf9.html" title="Last updated on Apr 24, 2024, 7:04 PM UTC (1661bf9)">Diff</a>

gru/lstm: Fix missing/incorrect variables and options use

---

index.bs

Introduce constraints for input operands, either directly (e.g. input's dataType can only be "float32" or "float16") or indirectly (e.g. weight's dataType must be the same as input's).
Fixes #283
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/646.html" title="Last updated on Apr 26, 2024, 6:03 AM UTC (ad239bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/646/d57e4ef...inexorabletash:ad239bc.html" title="Last updated on Apr 26, 2024, 6:03 AM UTC (ad239bc)">Diff</a>

Specify the operand data type constraints of operations

---

index.bs

Discussion on #492 (specifically, this comment https://github.com/webmachinelearning/webnn/issues/492#issuecomment-2076061596) concluded that this overload was not needed. Its behavior can be emulated by filling a buffer in JavaScript to be passed in with the buffer-based `constant()` overload
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/656.html" title="Last updated on Apr 25, 2024, 4:33 PM UTC (36e73bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/656/d57e4ef...a-sully:36e73bc.html" title="Last updated on Apr 25, 2024, 4:33 PM UTC (36e73bc)">Diff</a>

Remove sequential filling overload of constant()

---

index.bs

Fix #660
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/661.html" title="Last updated on Apr 29, 2024, 12:15 AM UTC (8350576)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/661/5b396da...huningxin:8350576.html" title="Last updated on Apr 29, 2024, 12:15 AM UTC (8350576)">Diff</a>

Bugfix: prelu should validate slope operand

---

index.bs

For gru()/gruCell() and lstm()/lstmCell(), a hiddenSize parameter is passed, a multiple of which defines a dimension of the output.
- This is sometimes implicitly validated by the presence of an option with the same dimension - but not always.
- Some underlying platforms operate on a single bias tensor, rather than the two bias/recurrentBias options present in the WebNN API. So the combined size needs to also be a valid dimension.
Introduce validation for all cases, validate the combined size, and add an explanation inline since this is subtle.
Fixes #625
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/644.html" title="Last updated on Apr 29, 2024, 4:26 PM UTC (9feeefb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/644/9f0f4 …

Validate the hidden size of GRU and LSTM operators

---

index.bs

- Some steps in gruCell() were comparing a rank vs. an expected dimension (e.g. "rank is not equal to 3 * hiddenSize"). Fix these!
- Rather than validating for example that rank = 2, shape[0] = N and shape[1] = M, just compare shape against « N, M ». This also implicitly fixes places that were inspecting shape[x] without validating the rank first. Done for: batchNormalization(), conv2d(), convTranspose2d(), gru(), gruCell(), lstm(), lstmCell().
- Some places did validate data type and rank, but only some or none of the dimensions. Make this consistent across the ops - at least, matching the existing prose. Done for gru(), gruCell(), instanceNormalization(), lstm(), lstmCell().
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/659.html" title="Last updated on May …

Simplify, correct, and add validation for GRU/LSTM and friends

---

index.bs

- Bug fix: Shapes should not be broadcast for logical "not" op.
- Bug fix: Validate transpose()'s permutation as a list, not operand.
- Conventions: Use "be" and "let" rather than "denote" and "store".
- Conventions: Use "otherwise" instead of "else" in steps.
- Conventions: Use "for each" not just "for" when iterating.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/672.html" title="Last updated on May 2, 2024, 8:10 PM UTC (8132deb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/672/aa5fac9...inexorabletash:8132deb.html" title="Last updated on May 2, 2024, 8:10 PM UTC (8132deb)">Diff</a>

Handful of algorithm and convention fixes

---

index.bs

Fixes #667
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/671.html" title="Last updated on May 1, 2024, 5:59 PM UTC (782afc7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/671/ecc55a3...a-sully:782afc7.html" title="Last updated on May 1, 2024, 5:59 PM UTC (782afc7)">Diff</a>

Remove uses of null as parameter to reshape() in code samples

---

index.bs

Fixes #658
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/664.html" title="Last updated on May 3, 2024, 11:58 PM UTC (082ceb3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/664/4165154...a-sully:082ceb3.html" title="Last updated on May 3, 2024, 11:58 PM UTC (082ceb3)">Diff</a>

Remove MLActivation parameters used for op fusion

---

index.bs

The algorithms for both conv2d() and convTranspose2d() used an `inputShape` local variable, but never defined it. Oops! The meaning was obvious, but we do need to define and initialize it to keep tooling happy.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/680.html" title="Last updated on May 6, 2024, 6:39 PM UTC (293ecef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/680/266eae1...inexorabletash:293ecef.html" title="Last updated on May 6, 2024, 6:39 PM UTC (293ecef)">Diff</a>

Add missing definitions of inputShape to conv2d algorithms

---

index.bs

Previously, a link to "transferred" was not scoped, and Bikeshed was silently linking to Verifiable Credentials Data Model v2.0's definition of the term. That term went away, so Bikeshed will now emit an error.
Fix by correctly scoping the link.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/679.html" title="Last updated on May 6, 2024, 6:32 PM UTC (ad6631c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/679/266eae1...inexorabletash:ad6631c.html" title="Last updated on May 6, 2024, 6:32 PM UTC (ad6631c)">Diff</a>

Build fix: Correct link for "transferred" term

---

index.bs

Per discussion in the issue, now that XNNPACK is updated there are no backends that disallow minValue == maxValue, so the issue can be resolved and spec note can be removed.
Resolves #396
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/684.html" title="Last updated on May 9, 2024, 6:59 PM UTC (31ce312)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/684/191a9de...inexorabletash:31ce312.html" title="Last updated on May 9, 2024, 6:59 PM UTC (31ce312)">Diff</a>

Remove note about interop issues with clamp()'s minValue == maxValue

---

index.bs

Fix #675
/cc @philloooo
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/685.html" title="Last updated on May 10, 2024, 1:23 PM UTC (0cbabce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/685/587af73...huningxin:0cbabce.html" title="Last updated on May 10, 2024, 1:23 PM UTC (0cbabce)">Diff</a>

Support int32 data type for 'indices' operand of 'gather' operator

---

docs/IssueTriage.md
index.bs

Suggested behavior matches the Chromium prototype implementation.
Fixes #681
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/683.html" title="Last updated on May 13, 2024, 4:22 PM UTC (057019c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/683/dafa2ba...inexorabletash:057019c.html" title="Last updated on May 13, 2024, 4:22 PM UTC (057019c)">Diff</a>

Validate no duplicate axes for reduction ops

---

index.bs

Noticed during a review of the Chromium prototype. These are all pretty obvious except for slice() where there is subtlety for 0-size dimensions. I added an issue linking to #391 since the steps will need to be revised depending on how that issue is resolved.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/690.html" title="Last updated on May 21, 2024, 4:09 PM UTC (962ca97)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/690/5e7d8cd...inexorabletash:962ca97.html" title="Last updated on May 21, 2024, 4:09 PM UTC (962ca97)">Diff</a>

Add missing validation for pad(), slice(), and split()

---

index.bs

As per discussion in #496, use name "logicalNot" to reduce ambiguity.
***
<a href="https://pr-preview.s3.amazonaws.com/shiyi9801/webnn/pull/692.html" title="Last updated on May 24, 2024, 5:55 AM UTC (c852d7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/692/960ae89...shiyi9801:c852d7f.html" title="Last updated on May 24, 2024, 5:55 AM UTC (c852d7f)">Diff</a>

Rename the logical operation "not" to "logicalNot"

---

index.bs

Fix #662
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/663.html" title="Last updated on Jun 5, 2024, 2:24 PM UTC (a3976ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/663/932b603...huningxin:a3976ae.html" title="Last updated on Jun 5, 2024, 2:24 PM UTC (a3976ae)">Diff</a>

Fix unidirectionally broadcast the shapes steps

---

index.bs

Follow-up to #664, without going so far as #689
Prior to #664, an `MLActivation` may be used for either op fusion or with recurrent operators (`lstm` and `gru`). Now it's only the latter, and some operators which may be created as an `MLActivation` no longer make sense to be passed as activations:
- `clamp`
- ~~`gelu`~~ (no longer being removed after feedback from reviewers)
- `softmax`
Note that this PR is not a _replacement_ for #689. That issue still stands on its own. Until we reach consensus on that issue, we should remove the `MLActivation`s which were clearly targeted at the op fusion use case.
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/703.html" title="Last updated on Jun 7, 2024, 4:29 PM UTC (e948f7e)">Preview</a> | <a …

Remove MLActivations definitely not usable with recurrent ops

---

index.bs

According to [audit result](https://docs.google.com/spreadsheets/d/1S5-bMWN1hDrkPGiHFCyX-OjcbEBj1a-aWNdtTQ2dcGg/edit?usp=sharing) of Chromium prototype, there are a few missing validations in the spec. This PR adds missing validations for conv2d() and convTranspose2d(). Other missing validations will be addressed by follow-up PRs.
@inexorabletash @fdwr , PTAL.
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/706.html" title="Last updated on Jun 12, 2024, 3:24 AM UTC (68cefc7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/706/74b9831...huningxin:68cefc7.html" title="Last updated on Jun 12, 2024, 3:24 AM UTC (68cefc7)">Diff</a>

Bugfix: Add missing validation for conv2d() and convTranspose2d()

---

CONTRIBUTING.md

This PR addresses an open from @a-sully in discussion thread: https://github.com/webmachinelearning/webnn/pull/695#issuecomment-2146022017
@fdwr @inexorabletash @anssiko , PTAL.

Add a section for updating an existing operation

---

index.bs
tools/lint.mjs

The Infra term "list/empty" is a verb (to empty); link to "list/is empty" when that's what is intended.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/708.html" title="Last updated on Jun 14, 2024, 9:31 PM UTC (5afa97c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/708/c00560f...inexorabletash:5afa97c.html" title="Last updated on Jun 14, 2024, 9:31 PM UTC (5afa97c)">Diff</a>

Link fix: Link to "is empty" not "empty" when an adjective is intended

---

index.bs

This change only adds the `MLDeviceType` *enum* (currently [implemented in Chromium-based browsers](https://chromium-review.googlesource.com/c/chromium/src/+/5330647) for early testing) and not yet quantize/dequantize operators, as those are valuable but technically orthogonal given they are *also* useful for GPU and given the enum alone is still useful for non-quantized models using float16 weights.
Of the 4 proposals from https://github.com/webmachinelearning/webnn/issues/623, we're starting with the simplest \#‌1 (simple enum with system-decided fallback), and if additional experience warrants more complexity, we'll re-evaluate the other options later.
Wording recommendations for device fallback are welcome. Neural processing units are novel compared with more generic compute devices …

Add MLDeviceType npu

---

index.bs

This makes it clearer how the example decompositions map to the methods they are defining - variables are explicitly named as parameters, or unpacked from the arguments.
Also fix code treating MLOperand's dataType() as a getter instead of a method.
No normative changes.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/709.html" title="Last updated on Jun 25, 2024, 1:33 AM UTC (392ae28)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/709/5c64074...inexorabletash:392ae28.html" title="Last updated on Jun 25, 2024, 1:33 AM UTC (392ae28)">Diff</a>

Write example decompositions as complete functions

---

index.bs

With two MLActivation-vending overloads removed, two subsection headers could be removed.
But that pointed out where ordering for the "emulation" section in overloaded methods was inconsistent. So tidy that up too.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/711.html" title="Last updated on Jun 25, 2024, 11:37 PM UTC (32a6437)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/711/588a728...inexorabletash:32a6437.html" title="Last updated on Jun 25, 2024, 11:37 PM UTC (32a6437)">Diff</a>

Remove unnecessary subsections, make order consistent

---

docs/SpecCodingConventions.md
index.bs

Outside of algorithms, the spec is mostly consistent about formatting expressions using `backticks`; tidy up the few exceptions and add a convention note.
Also, apply the existing convention to format tensor shape definitions using *[ ... ]* consistently.
Also also, since it commonly precedes an expression, fix "as follow" to be "as follows" - the latter is the correct English form for this phrase, per style guides, even if multiple items follow it.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/710.html" title="Last updated on Jun 26, 2024, 7:10 PM UTC (cf6188a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/710/f7ceef9...inexorabletash:cf6188a.html" title="Last updated on Jun 26, 2024, 7:10 PM UTC (cf6188a)">Diff</a>

Style: Consistently use backticks for expressions in prose

---

index.bs

Fixes #713 : trivial replacement of DOMString (names) with USVString.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/715.html" title="Last updated on Jul 2, 2024, 7:32 AM UTC (5a614bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/715/08719e1...zolkis:5a614bd.html" title="Last updated on Jul 2, 2024, 7:32 AM UTC (5a614bd)">Diff</a>

Fix #713: DOMString to USVString

---

index.bs

(This PR was raised by @philloooo in [CL-5679616 review](https://chromium-review.googlesource.com/c/chromium/src/+/5679616/6/third_party/blink/renderer/modules/ml/ml_context.idl#43))
@wacky6 suggested using `trueValue` `falseValue` to indicate the values are picked based on true/false of `condition` in [CL-5039655 review](https://chromium-review.googlesource.com/c/chromium/src/+/5039655/2/third_party/blink/renderer/modules/ml/webnn/ml_graph_builder.idl#218). Also the current Chromium implementation uses names `trueValue` and `falseValue`.
***
<a href="https://pr-preview.s3.amazonaws.com/shiyi9801/webnn/pull/719.html" title="Last updated on Jul 9, 2024, 5:43 AM UTC (a8e5d89)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/719/3a916f2...shiyi9801:a8e5d89. …

Rename where()'s parameters "input" and "other" to "trueValue" and "falseValue"

---

index.bs

Fixes #652 
This removes the `selectLastIndex` parameter from argMin and argMax, given that the CoreML backend has no guarantee of return value in case of ties.
@fdwr  please take a look :)
***
<a href="https://pr-preview.s3.amazonaws.com/philloooo/webnn/pull/722.html" title="Last updated on Jul 11, 2024, 6:17 PM UTC (1f06e41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/722/fe96a78...philloooo:1f06e41.html" title="Last updated on Jul 11, 2024, 6:17 PM UTC (1f06e41)">Diff</a>

Remove argmin/max selectLastIndex parameter

---

index.bs
tools/lint.mjs

Also adds a lint rule to enforce that every argument given in IDL is linked to a prose definition for it, and a lint rule to look for argument definitions that don't match their methods.
Fixes #574
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/721.html" title="Last updated on Jul 12, 2024, 6:46 PM UTC (c2001d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/721/af67a72...inexorabletash:c2001d9.html" title="Last updated on Jul 12, 2024, 6:46 PM UTC (c2001d9)">Diff</a>

Style: Link method argument definitions

---

index.bs

* Throw if the passed buffer source is detached.
* Explicitly rethrow if transfering throws.
The callers already handle failure.
Fixes #351
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/723.html" title="Last updated on Jul 12, 2024, 6:08 PM UTC (6edc5e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/723/af67a72...inexorabletash:6edc5e8.html" title="Last updated on Jul 12, 2024, 6:08 PM UTC (6edc5e8)">Diff</a>

Define error handling of MLNamedArrayBufferViews transfer algorithm

---

index.bs

Fixes #567
If `MLGraphBuilder.build()` results in anything other than a `TypeError` - e.g. it successfully resolves with an or `MLGraph` or rejects with a `NotSupportedError` - that `MLGraphBuilder` has now been "built" and all subsequent methods will now reject with an `InvalidStateError`.
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/717.html" title="Last updated on Jul 10, 2024, 6:20 PM UTC (57e3962)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/717/3a916f2...a-sully:57e3962.html" title="Last updated on Jul 10, 2024, 6:20 PM UTC (57e3962)">Diff</a>

Allow MLGraphBuilder.build() to be called only once

---

index.bs
tools/lint.mjs

Previously, the test ensuring that algorithm steps end in '.' or ':' looked at the Bikeshed source. This didn't handle word wrapping. While we prefer not to word wrap, that shouldn't cause this test to fail.
Make the test analyse the DOM instead.
Also, fix some unrelated Bikeshed/lint failures introduced in f08f9f7382a5db03566205825174a3204eb90a8f
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/727.html" title="Last updated on Jul 16, 2024, 11:56 PM UTC (8ae6441)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/727/f08f9f7...inexorabletash:8ae6441.html" title="Last updated on Jul 16, 2024, 11:56 PM UTC (8ae6441)">Diff</a>

Lint: Improve logic for validating algorithm steps.

---

index.bs

Inspired by the ONNX documentation[1], outline what inference-time casts are well-defined and which are implementation-defined for out-of-range values.
Fixes #489
1: https://onnx.ai/onnx/operators/onnx__Cast.html
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/726.html" title="Last updated on Jul 17, 2024, 4:44 PM UTC (7dc738d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/726/c9e70f6...inexorabletash:7dc738d.html" title="Last updated on Jul 17, 2024, 4:44 PM UTC (7dc738d)">Diff</a>

Clarify the cast() op behavior between different data types

---

index.bs

fixes #629 
- Changes argmin/argmax to take scalar axis instead of axes list. 
- Remove default value for `axis`, so now it becomes positional argument
@fdwr @huningxin  please take a look :)
***
<a href="https://pr-preview.s3.amazonaws.com/philloooo/webnn/pull/724.html" title="Last updated on Jul 16, 2024, 9:23 PM UTC (9c96d6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/724/dbb9d1c...philloooo:9c96d6f.html" title="Last updated on Jul 16, 2024, 9:23 PM UTC (9c96d6f)">Diff</a>

change argmin/argmax to take scalar axis

---

.github/workflows/auto-publish.yml
tools/lint.mjs

Help catch errors by running our bespoke lint tool after the normal publish/deploy. Ideally, in the future this would be integrated into spec-prod to avoid some duplicate work, and made more modular and robust. But hopefully it's better than nothing!

Workflow: Add steps to run tools/lint.mjs after spec is built

---

docs/SpecCodingConventions.md
index.bs

Per the spec processing model, algorithms don't usually deal with a sequence<T> type; the JS value has been converted to an Infra list. So try to avoid using that term in prose, especially as it is confusing for recurrent operators which have temporal sequences as well. But do call out an exception: unpacking unions.
When used in an IDL type description, though, do linkify it.
Fix a few other grammar/link glitches, too.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/729.html" title="Last updated on Jul 18, 2024, 11:49 PM UTC (9ffdda7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/729/19762ed...inexorabletash:9ffdda7.html" title="Last updated on Jul 18, 2024, 11:49 PM UTC (9ffdda7)">Diff</a>

Avoid "sequence" in prose, linkify use in types

---

index.bs

As promised, the local algorithm "detachable" migrated to WebIDL[1], so we can drop our copy of the algorithm and reference WebIDL's version instead, which is identical except for a name change[3].
(If you're building the spec locally and run into errors, force a Bikeshed update[2] to ensure you have the latest indexes.)
1: https://github.com/whatwg/webidl/commit/d6927d59da4e1d2f9499dae1575c710ae50c3f18
2: https://speced.github.io/bikeshed/#updating-bikeshed
3: https://github.com/whatwg/webidl/pull/1419#discussion_r1681950171
Ref: #351
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/732.html" title="Last updated on Jul 19, 2024, 5:17 PM UTC (da3f620)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/732/6be80a4...inexorabletash: …

Reference newly landed WebIDL "transferable" definition

---

index.bs

The spec should only reference IDL types in prose when dealing with binding, e.g. in unions, and maybe internal slots. When discussing values in tensors, just be explicit and don't try to link to a definition that doesn't really apply.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/735.html" title="Last updated on Jul 22, 2024, 11:55 PM UTC (3a6f73d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/735/487a992...inexorabletash:3a6f73d.html" title="Last updated on Jul 22, 2024, 11:55 PM UTC (3a6f73d)">Diff</a>

Editorial: Don't reference IDL boolean for values in tensors

---

index.bs

This typo issue was caught by https://chromium-review.googlesource.com/c/chromium/src/+/5668527/comment/b4a20d72_b987e05c/.
@huningxin @anssiko PTAL, thanks.
***
<a href="https://pr-preview.s3.amazonaws.com/BruceDai/webnn/pull/736.html" title="Last updated on Jul 23, 2024, 10:01 AM UTC (5c97f54)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/736/dcc423d...BruceDai:5c97f54.html" title="Last updated on Jul 23, 2024, 10:01 AM UTC (5c97f54)">Diff</a>

Fixed typo

---

index.bs

fixes #653
Add outputDataType to `MLArgMinMaxOptions` and defaults to `int32`. Given `opSupportLimits` is not added to spec yet, no validation steps is done to `outputDataType` right now.
@fdwr @huningxin
***
<a href="https://pr-preview.s3.amazonaws.com/philloooo/webnn/pull/730.html" title="Last updated on Jul 23, 2024, 12:06 AM UTC (26aa1fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/730/92ff390...philloooo:26aa1fd.html" title="Last updated on Jul 23, 2024, 12:06 AM UTC (26aa1fd)">Diff</a>

Add outputDataType to argmin/argmax

---

index.bs

fixes #734
Update `valid dimension` definition to be in the range of `long` and greater than 0.
@fdwr @huningxin
***
<a href="https://pr-preview.s3.amazonaws.com/philloooo/webnn/pull/738.html" title="Last updated on Jul 23, 2024, 7:41 PM UTC (11c994f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/738/dbb9d1c...philloooo:11c994f.html" title="Last updated on Jul 23, 2024, 7:41 PM UTC (11c994f)">Diff</a>

Update dimension valid range to signed integer

---

index.bs

The only non-trivial bits are a few cases where in the previous steps the shape was calculated after the MLOperandDescriptor was created, but this would not be an observable change to script.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/737.html" title="Last updated on Jul 25, 2024, 7:53 PM UTC (6cba044)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/737/71dd440...inexorabletash:6cba044.html" title="Last updated on Jul 25, 2024, 7:53 PM UTC (6cba044)">Diff</a>

Add helper for creating MLOperandDescriptor to simplify steps

---

index.bs

- Just say "broadcast" not "broadcasted"; Merriam-Webster says the former is preferable.
- Make prelu() bidirectionally broadcast instead of unidirectionally broadcast, as it's not an obvious unidirectional case.
- Make preamble more consistent across operations in calling out broadcasting and stating the requirements for input tensors.
- Shorten algorithm link, e.g. from "...broadasting the shapes A's shape and B's shape" to just "...broadcasting A's shape and B's shape"
Resolves #590

Make prelu() bidirectionally broadcast, improve broadcast wording

---

index.bs

This adds an internal 'label' property to the operators that are created as a graph is constructed, which MAY (in the RFC 2119 sense) be used by implementations in async error messages. Developers populate this via a 'label' member in the options dictionary for MLGraphBuilder methods.
A new MLOperatorOptions dictionary is defined, and all existing options dictionaries now inherit from this, and all relevant methods now take an options dictionary.
This is based on the Chromium prototype by @lisa0314 
Fixes #585
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/742.html" title="Last updated on Jul 28, 2024, 2:10 AM UTC (bfcc813)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/742/ef78826...inexorabletash:bfcc813.html" title="Last …

Add optional operator labels for more diagnosable error messages

---

index.bs

Improve the description of the reduction ops:
- Give in-line definition for L1/L2.
- Make "input values" slightly clearer.
- Explicitly note that if the input is a scalar, so is the output.
- State how the reduction function is applied for empty axes.
- Standardize on "reduction operation" not "reduce operation".
- Don't style list of reduction ops as non-normative note.
Fixes #740
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/741.html" title="Last updated on Jul 30, 2024, 5:22 PM UTC (f982418)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/741/8734bea...inexorabletash:f982418.html" title="Last updated on Jul 30, 2024, 5:22 PM UTC (f982418)">Diff</a>

Clarify reduction with empty axes and scalar input

---

index.bs

All input integers have [EnforceRange] applied to prevent weirdness... except softmax()'s axis argument. Already present in the Chromium prototype implementation; it looks like this argument was just missed in 6023741.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/746.html" title="Last updated on Jul 30, 2024, 8:41 PM UTC (2027157)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/746/4697a0d...inexorabletash:2027157.html" title="Last updated on Jul 30, 2024, 8:41 PM UTC (2027157)">Diff</a>

Bug fix: softmax()'s axis argument should EnforceRange

---

index.bs

Fixs #624
This allow any arbitrary axes as long as they are valid dimensions for resample2d. Remove restriction on it to be the spacial dimensions.
[Chromium prototype](https://chromium-review.googlesource.com/c/chromium/src/+/5798093)
@fdwr @huningxin
***
<a href="https://pr-preview.s3.amazonaws.com/philloooo/webnn/pull/752.html" title="Last updated on Aug 22, 2024, 5:39 PM UTC (471cc12)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/752/d7d0363...philloooo:471cc12.html" title="Last updated on Aug 22, 2024, 5:39 PM UTC (471cc12)">Diff</a>

Allow arbitrary axes for resample2d

---

index.bs

Fixes #463 by defining opSupportLimits.
Defering rankRange until we implement the prototype.
@reillyeon @huningxin @fdwr
***
<a href="https://pr-preview.s3.amazonaws.com/philloooo/webnn/pull/755.html" title="Last updated on Aug 30, 2024, 4:55 PM UTC (4099c2a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/755/355c38d...philloooo:4099c2a.html" title="Last updated on Aug 30, 2024, 4:55 PM UTC (4099c2a)">Diff</a>

Define opSupportLimits()

---

index.bs

`MLLstmCellSupportLimits.outputs` reflects that lstmCell returns a sequence of operands.
Fix https://github.com/webmachinelearning/webnn/pull/755#discussion_r1740347722
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/757.html" title="Last updated on Sep 2, 2024, 5:42 AM UTC (9e2dfc6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/757/49eeebf...huningxin:9e2dfc6.html" title="Last updated on Sep 2, 2024, 5:42 AM UTC (9e2dfc6)">Diff</a>

Bugfix: Rename member `output` to `outputs` of `MLLstmCellSupportLimits`

---

index.bs

Fixes #669
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/676.html" title="Last updated on Sep 18, 2024, 4:29 AM UTC (870885a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/676/d7d0363...a-sully:870885a.html" title="Last updated on Sep 18, 2024, 4:29 AM UTC (870885a)">Diff</a>

Rename MLOperandDescriptor's "dimensions" key to "shape"

---

index.bs

Fixes #775
***
<a href="https://pr-preview.s3.amazonaws.com/BruceDai/webnn/pull/776.html" title="Last updated on Oct 30, 2024, 12:52 AM UTC (0a64a13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/776/9287c0b...BruceDai:0a64a13.html" title="Last updated on Oct 30, 2024, 12:52 AM UTC (0a64a13)">Diff</a>

Bugfix: Fix the error of opSupportLimits for split op

---

index.bs

Fixes #666
Implements the changes proposed in https://github.com/webmachinelearning/webnn/issues/666#issuecomment-2342019337 while simplifying the declaration of these getters to use the pattern suggested in https://webidl.spec.whatwg.org/#idl-frozen-array
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/774.html" title="Last updated on Oct 29, 2024, 8:32 PM UTC (a8b0b3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/774/9287c0b...a-sully:a8b0b3d.html" title="Last updated on Oct 29, 2024, 8:32 PM UTC (a8b0b3d)">Diff</a>

Convert MLOperand methods into readonly attributes

---

index.bs
tools/lint.mjs

Infra[1] grew syntax "Let « |var1|, |var2|, ... » be |list|." which simplifies enum-driven unpacking. Use it! Also add corresponding lint validation.
One usage guarded by an "if" test appeared to have inverted condition, so fix that too.
1: https://infra.spec.whatwg.org/#example-list-multiple-assignment
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/777.html" title="Last updated on Nov 5, 2024, 7:46 PM UTC (85ab172)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/777/673c6b5...inexorabletash:85ab172.html" title="Last updated on Nov 5, 2024, 7:46 PM UTC (85ab172)">Diff</a>

Wording: Use newfangled multiple assignment from lists

---

index.bs

This will help direct readers who see the console.warn deprecation messages to the right place. To be removed when the specification patches land.
FYI @a-sully
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/781.html" title="Last updated on Nov 7, 2024, 8:54 AM UTC (5b6e8eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/781/673c6b5...5b6e8eb.html" title="Last updated on Nov 7, 2024, 8:54 AM UTC (5b6e8eb)">Diff</a>

Add deprecation warning for compute() -> dispatch()

---

index.bs
tools/lint.mjs

Not referenced normatively, but helpful at-a-glance information. This should be redundant with existing per-op documentation.
As discussed in https://github.com/webmachinelearning/webnn/pull/657#discussion_r1843061102
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/789.html" title="Last updated on Nov 19, 2024, 8:52 PM UTC (b63ed1a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/789/c237cf1...inexorabletash:b63ed1a.html" title="Last updated on Nov 19, 2024, 8:52 PM UTC (b63ed1a)">Diff</a>

Include output operand type/rank in op constraint tables

---

mltensor-explainer.md

Update the explainer to point to #778 instead of #477, which is now closed

Editorial: Link to error handling proposal from the MLTensor explainer

---

index.bs

This PR specifies key methods related to `MLTensor`, while hand-waving over much of the juicy details, such as how to actually specify the `MLContext`'s timeline (#529)
My hope is that this is a mostly-straightforward improvement which is "good enough" to allow us to remove `MLContext.compute()` as well as providing a more concrete starting point for more detailed discussions about e.g. specifying timelines in follow-up PRs
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/787.html" title="Last updated on Nov 22, 2024, 7:55 PM UTC (493ede3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/787/d4b4e9d...a-sully:493ede3.html" title="Last updated on Nov 22, 2024, 7:55 PM UTC (493ede3)">Diff</a>

Specify MLTensor

---

index.bs

Fix #788
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/790.html" title="Last updated on Nov 27, 2024, 6:21 AM UTC (0bd2d0a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/790/c237cf1...huningxin:0bd2d0a.html" title="Last updated on Nov 27, 2024, 6:21 AM UTC (0bd2d0a)">Diff</a>

Use `AllowSharedBufferSource` for `MLGraphBuilder.constant()`

---

index.bs

Fixes #791. Made possible by #787 which specified `dispatch()`
The changes proposed in #786 have also been rolled into this PR, since they can't really be decoupled from `compute()` removal at this point
I've tried to keep this PR minimal and focused on removing algorithms and IDL definitions which are no longer relevant. The spec still contains lots of normative text which was written with `compute()` in mind which doesn't map as well to `dispatch()` - specifically text which contains assumptions about how graph execution relates to compute devices. I've lightly updated some of this text where necessary to match the `dispatch()` paradigm, but my intention is to avoid opening the can of worms that is #749 in this PR :)
***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/795 …

Remove the MLContext.compute() method

---

index.bs

A local change I had that needed dusting off. It's probably worth reviewing/merging, but not urgently.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/796.html" title="Last updated on Dec 4, 2024, 12:49 AM UTC (8d8d43a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/796/4e80205...inexorabletash:8d8d43a.html" title="Last updated on Dec 4, 2024, 12:49 AM UTC (8d8d43a)">Diff</a>

Complain about RFC2119 terms, and fix usage

---

index.bs
tools/lint.mjs

Based on @mingmingtasd's work in the Chromium prototype implementation. 
`MLContext` gains a `destroy()` method and a `lost` promise attribute. Calling `destroy()` releases resources for the context itself and any associated `MLGraph`s and `MLTensor`s, and any outstanding `build()` requests for an associated `MLGraphBuilder` are aborted. The `lost` attribute then resolves, and any future use of the context fails. If the context is lost for other reasons, the same behavior occurs (releasing associated resources), and the `lost` promise provides an implementation-defined message explaining the reason. 
`MLGraph` similarly gains a `destroy()` attribute. When destroyed - either by an explicit call, or because the associated context is lost - then any outstanding `dispatch()` requests using …

Specify destroy() methods and behavior around context loss and error reporting

---

index.bs

This PR is to fix **lstm** emulation error of #801.
@fdwr @huningxin PTAL, thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/BruceDai/webnn/pull/802.html" title="Last updated on Jan 16, 2025, 2:46 AM UTC (95bbbee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/802/df555e1...BruceDai:95bbbee.html" title="Last updated on Jan 16, 2025, 2:46 AM UTC (95bbbee)">Diff</a>

Bugfix: Fix emulation error of lstm by 'backward' and 'both' direction options

---

security-privacy.md

Noticed this hasn't been updated.  @inexorabletash  @huningxin @fdwr ?

update privacy readme for opSupportLimits

---

index.bs

A pair of steps in "create pooling operation" had an "If" condition with multiple clauses, and a subsequent "Otherwise" step that needs to apply if only the first clause is true. Rework the lines to correct the logic, and also align with subsequent argument validation.
Also, put "Otherwise, ..." steps on their own line consistently.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/806.html" title="Last updated on Jan 26, 2025, 8:14 AM UTC (4d5898d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/806/17a44e2...inexorabletash:4d5898d.html" title="Last updated on Jan 26, 2025, 8:14 AM UTC (4d5898d)">Diff</a>

Editorial: Fix glitch with otherwise clause in pool op creation

---

index.bs
tools/lint.mjs

"Realm" is an ECMAScript concept best explained in https://html.spec.whatwg.org/multipage/webappapis.html#realms-and-their-counterparts Newly created JS objects must be associated with a Realm; while older specs didn't do this explicitly, best practice is to be explicit about this, especially for steps running "in parallel", or in algorithms separate from method steps. Do so!
This also adds lint tests to try and catch future violations. Note that dictionaries (e.g. MLOperatorDescriptor) are Infra "ordered maps" it the body of spec algorithms, not JS objects, so they don't have a realm. Conversion to a JS object when returning a dictionary to script is handled by WebIDL bindings logic.
Also note that DOMExceptions, either thrown or as promise rejection values, are not given a realm. This …

Ensure object creation specifies the realm

---

docs/SpecCodingConventions.md
index.bs
tools/lint.mjs

This PR addresses the changes outlined in #783
To make reviewing easier I've left it as a chain of commits, each one tackling just one stylistic change.
Resolves #783
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/797.html" title="Last updated on Jan 30, 2025, 4:47 PM UTC (71cce54)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/797/2139976...inexorabletash:71cce54.html" title="Last updated on Jan 30, 2025, 4:47 PM UTC (71cce54)">Diff</a>

Editorial: Various style and wording tweaks

---

index.bs

Resolves #749. 
Addresses #302, #350.
See also the [device selection explainer](https://github.com/webmachinelearning/webnn/blob/main/device-selection-explainer.md).
This is a minimal change for now. It may require changing prose or adding more details / instructions in related sections/algorithms.
***
<a href="https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/809.html" title="Last updated on Feb 6, 2025, 2:58 PM UTC (f4b8402)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/809/4acd8e4...zolkis:f4b8402.html" title="Last updated on Feb 6, 2025, 2:58 PM UTC (f4b8402)">Diff</a>

Remove MLDeviceType

---

index.bs

This gives formal definitions for the `nearest-neighbor` and `linear` interpolation modes. The definitions are based on text given by @fdwr and baseline implementation by @BruceDai and independently verified.
Resolves #358
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/816.html" title="Last updated on Feb 13, 2025, 5:41 PM UTC (8a34038)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/816/74b5ae5...inexorabletash:8a34038.html" title="Last updated on Feb 13, 2025, 5:41 PM UTC (8a34038)">Diff</a>

Clarify interpolation algorithms for resample2d

---

index.bs

This is primarily to address an issue with "create pooling operation" where the input height and width are used before being calculated, but applies the same flattening across single use algorithms specific to shape calculation. The remaining helpers are either used multiple times by the same op algorithm (e.g. handling a single dimension) or shared across ops (e.g. reduction and argMin/argMax).
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/814.html" title="Last updated on Feb 3, 2025, 7:03 PM UTC (1c3f97b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/814/74b5ae5...inexorabletash:1c3f97b.html" title="Last updated on Feb 3, 2025, 7:03 PM UTC (1c3f97b)">Diff</a>

Editorial: Inline shape calculation algorithms only used once

---

index.bs

The list equality definition is intentionally written in the same style as the Infra definition for set equality; the algorithm can be removed once https://github.com/whatwg/infra/issues/664 is settled.
Resolves #792
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/813.html" title="Last updated on Feb 3, 2025, 7:10 PM UTC (1e78c49)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/813/74b5ae5...inexorabletash:1e78c49.html" title="Last updated on Feb 3, 2025, 7:10 PM UTC (1e78c49)">Diff</a>

Define equality for lists and MLOperandDescriptors

---

index.bs

Two glitches introduced in a88bb0e where validation steps were inlined; the out-of-line steps returned "failure" but now that they're inlined they need to explicitly throw. My bad.
Also, when referring to the contents of a list, the Infra term is "items", so use that and linkify it, rather than the more generic "elements" term. We more consistently use "elements" when referring to the contents of a tensor anyway.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/819.html" title="Last updated on Feb 18, 2025, 7:09 PM UTC (3abc98f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/819/d17fe35...inexorabletash:3abc98f.html" title="Last updated on Feb 18, 2025, 7:09 PM UTC (3abc98f)">Diff</a>

Fix returning failure from methods, and use "item" for lists

---

index.bs

A follow-on to #706 and the
[audit](https://docs.google.com/spreadsheets/d/1S5-bMWN1hDrkPGiHFCyX-OjcbEBj1a-aWNdtTQ2dcGg) by @huningxin that adds validation steps to several ops identified for edge cases in the Chromium prototype implementation.
This touches the following ops:
- convTranspose2d - outputSizes items must be valid dimensions
- lstm - steps must be greater than 0
- pool2d - windowDimensions must be greater than 0
- pool2d - outputSizes items must be valid dimensions
- pool2d - specified output sizes must be floor() or ceil() of calculated output sizes
- split - splits (if a number) must be greater than 0
Fixes #818 as well.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/820.html" title="Last updated on Feb 21, 2025, 9:04 PM UTC …

Add missing validation steps for several ops

---

device-selection-explainer.md

Updated the device selection explainer with the latest discussions.
Fixed links that refer to past spec versions.

Update device selection explainer

---

tools/lint.mjs

New checks:
- Validate that constraint table links from steps are reasonable.
- Validate that constraint tables use links not styles for params.
Improved checks:
- Make duplicate word detection case insensitive and match at start/end of lines.
Internal changes:
- Massage HTML to allow node-html-parser to handle tables.
- Improve output when matching at line boundaries.
- Comment checks with "Generic" or "WebNN".

Lint: Add additional checks and improve HTML parsing

---

index.bs

As noted in the issue, it is convenient allow Uint8Array as a generic way of representing a slice of an ArrayBuffer, instead of always requireing either an ArrayBuffer to be passed (which may involve copying), or constructing a view type corresponding to the dataType.
Resolves #825
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/829.html" title="Last updated on Mar 13, 2025, 9:56 PM UTC (1668590)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/829/3dd9216...inexorabletash:1668590.html" title="Last updated on Mar 13, 2025, 9:56 PM UTC (1668590)">Diff</a>

Allow Uint8Array in constant() etc. as a generic ArrayBufferView type

---

tools/lint.mjs
tools/package.json

Dictionary types need special treatment in a lint rule verifying that realms are used correctly. This requires knowing which types are dictionaries vs. interfaces. This was previously hard-coded, which is a maintenance burden.
Improve this by pulling in the webidl2.js library and using it to parse (and validate!) the spec's WebIDL, which gives us a list of dictionary types.

Tooling: Use WebIDL2 parser when linting to identify dictionaries

---

index.bs

Add rankRange to opSupportLimits() by renaming MLSupportLimits to MLDataTypeLimits (still used for inputs, constants, and output operands), and deriving MLTensorLimits (used for tensor operands) which adds the new member as a MLRankRange dictionary.
This also adds a note about an operand's allowed data types and ranks, indicating the implementations may extend or impose limits. 
In addition, maxTensorByteLength is added to the MLOpSupportLimits dictionary. 
Based on the work in Chromium by Reilly Grant, Wei Wang, and Junwei Fu.
Resolves #456
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/828.html" title="Last updated on Apr 3, 2025, 11:37 PM UTC (e023048)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/828/5daf9d7...inexorabl …

Add rankRange to opSupportLimits()

---

index.bs

As noted in the issue, sharing weights between graphs is a effective way to enable reuse of device buffers, allowing web developers to manage weight data in graphs similarly to other input or output buffers.
@fdwr @huningxin @reillyeon 
Based on the work in Chromium by Austin Sullivan.
Resolves #760
***
<a href="https://pr-preview.s3.amazonaws.com/bbernhar/webnn/pull/830.html" title="Last updated on Apr 21, 2025, 9:22 PM UTC (8b972ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/830/69bb88d...bbernhar:8b972ff.html" title="Last updated on Apr 21, 2025, 9:22 PM UTC (8b972ff)">Diff</a>

Allow tensors for graph constants.

---

index.bs

Fix three instances where an option was incorrectly linked, e.g. MLGatherOptions/axis when the variable in question was a MLScatterOptions.
Also, fix a simple typo.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/839.html" title="Last updated on Apr 25, 2025, 10:48 PM UTC (2aece7d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/839/4771d50...inexorabletash:2aece7d.html" title="Last updated on Apr 25, 2025, 10:48 PM UTC (2aece7d)">Diff</a>

Editorial: Fix some option links and one typo

---

index.bs

Per discussion in the linked issues and working group, drop "symmetric" padding since it is not widely supported by backends, isn't used by notable models, and can be emulated. Also for non-constant padding, backends typically impose restrictions on the amount of padding to reasonable values based on the input size, so incorporate those limits too.
Resolves #377. Resolves #739.
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/843.html" title="Last updated on Apr 29, 2025, 11:31 PM UTC (9129a11)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/843/b152d46...inexorabletash:9129a11.html" title="Last updated on Apr 29, 2025, 11:31 PM UTC (9129a11)">Diff</a>

Restrict padding options to better match backend limits

---

mltensor-explainer.md

Proposes an IDL change to reflect our current [implementation](https://chromium-review.googlesource.com/c/chromium/src/+/6064345) for WebGPU interop. Specifically, it moves the responsibility of producing a interop `GPUBuffer` into WebNN.
Before
```js
dictionary GPUImportedTensorDescriptor : GPUObjectDescriptorBase {
required MLTensor source;
};
partial interface GPUDevice {
Promise<GPUBuffer> importExternalBuffer(GPUImportedTensorDescriptor descriptor);
}
```
After
```js
partial interface MLContext {
Promise<GPUBuffer> exportToWebGPU(MLTensor source);
}
```
This change achieves the following:
- Eliminates the need to modify (or extend) the WebGPU spec for an experimental WebNN feature.
- Gives WebNN WG flexibility to iterate/extend the interop API along with the WebNN IDL (ex. new …

MLTensor explainer: replace "import buffer" with "export tensor"

---

index.bs

Fix #845
***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/848.html" title="Last updated on May 16, 2025, 2:16 AM UTC (fe7fa56)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/848/2baa084...huningxin:fe7fa56.html" title="Last updated on May 16, 2025, 2:16 AM UTC (fe7fa56)">Diff</a>

Bugfix: Support `int64` for `abs`, `neg`, `sign`, `prelu` and `relu`

---

index.bs

Fix #837
Do we have other Unicode strings in this specification that could be affected similarly to `label`?
***
<a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/pull/851.html" title="Last updated on May 22, 2025, 10:06 AM UTC (7788774)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/851/9b84267...7788774.html" title="Last updated on May 22, 2025, 10:06 AM UTC (7788774)">Diff</a>

Note Unicode sequences in Security Considerations

---

device-selection-explainer.md

Adds a new subsection "Device Preference Use Cases" to the device-selection-explainer.md document.
This subsection details several use cases for device selection preferences, mapping them to the preferences discussed in the W3C WebML WG minutes of 2025-05-08 (https://www.w3.org/2025/05/08-webmachinelearning-minutes.html#2ec0).
The use cases cover:
- Preferring CPU
- Preferring NPU
- Preferring GPU
- Maximizing performance
- Maximizing power efficiency
- Minimizing overall system power
Future-proof device names ("where JS and Wasm execute", "where WebGL and WebGPU programs execute", "other") are used in the descriptions.

Add device preference use cases to explainer

---

index.bs

This PR is to fix #863.
@fdwr  @huningxin PTAL, thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/BruceDai/webnn/pull/864.html" title="Last updated on Jun 9, 2025, 9:21 AM UTC (958095d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/864/61d4d5a...BruceDai:958095d.html" title="Last updated on Jun 9, 2025, 9:21 AM UTC (958095d)">Diff</a>

Bugfix: Fix typos in dequantizeLinear's decomposition code

---

index.bs

- Fixes #817.
- Addresses incomplete `quantizeLinear` emulation step.
```diff
partial interface MLGraphBuilder
{
...
+   MLOperand roundEven(MLOperand input, optional MLOperatorOptions options = {});
...
};
```
`RHE` **r**ound **h**alves to nearest **e**ven:
- [DML ROUND](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_element_wise_round_operator_desc) with [DML_ROUNDING_MODE_HALVES_TO_NEAREST_EVEN](https://learn.microsoft.com/en-us/windows/win32/api/directml/ne-directml-dml_rounding_mode)
- [tfl.round (TFL::RoundOp)](https://www.tensorflow.org/mlir/tfl_ops#tflround_tflroundop) 🤔 \*It's not clearly documented for TFLite, but I'm presuming TFL follows TF in using RHE.
- [ONNX Round](https://onnx.ai/onnx/operators/onnx__Round.html)
- [PyTorch …

Add `roundEven` operator
